// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: microservice.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from microservice.proto</summary>
public static partial class MicroserviceReflection {

  #region Descriptor
  /// <summary>File descriptor for microservice.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MicroserviceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJtaWNyb3NlcnZpY2UucHJvdG8aGWdvb2dsZS9wcm90b2J1Zi9hbnkucHJv",
          "dG8inwcKB1JlcXVlc3QSEwoGTW9kdWxlGAEgASgJSACIAQESEgoFUGFyYW0Y",
          "AiABKAlIAYgBARIUCgdQYXJhbUlEGAMgASgJSAKIAQESFQoIUGFyYW1JREQY",
          "BCABKAlIA4gBARITCgZBY3Rpb24YBSABKAlIBIgBARIgCgRBcmdzGAYgAygL",
          "MhIuUmVxdWVzdC5BcmdzRW50cnkSEQoEUGF0aBgHIAEoCUgFiAEBEhIKBVRv",
          "a2VuGAggASgJSAaIAQESEQoEU2lnbhgJIAEoCUgHiAEBEhAKA1NJRBgKIAEo",
          "CUgIiAEBEg8KAklQGAsgASgJSAmIAQESFgoJVXNlckFnZW50GAwgASgJSAqI",
          "AQESFgoJVG9rZW5UeXBlGA0gASgJSAuIAQESFgoJVGltZVN0YW1wGA4gASgF",
          "SAyIAQESFQoITGFuZ3VhZ2UYDyABKAlIDYgBARIXCgpBUElWZXJzaW9uGBAg",
          "ASgJSA6IAQESEwoGTWV0aG9kGBEgASgJSA+IAQESEAoDVUlEGBIgASgJSBCI",
          "AQESFAoHSXNBZG1pbhgTIAEoBUgRiAEBEhcKClNlc3Npb25FbmQYFCABKAVI",
          "EogBARIWCglDb21wbGV0ZWQYFSABKAVIE4gBARIVCghSZWFkb25seRgWIAEo",
          "BUgUiAEBEhEKBEZpbGUYFyABKAxIFYgBARIVCghGaWxlbmFtZRgYIAEoCUgW",
          "iAEBEg0KBUZpbGVzGBkgAygJEiEKAklSGBogASgLMhAuSW50ZXJuYWxSZXF1",
          "ZXN0SBeIAQEaQQoJQXJnc0VudHJ5EgsKA2tleRgBIAEoCRIjCgV2YWx1ZRgC",
          "IAEoCzIULmdvb2dsZS5wcm90b2J1Zi5Bbnk6AjgBQgkKB19Nb2R1bGVCCAoG",
          "X1BhcmFtQgoKCF9QYXJhbUlEQgsKCV9QYXJhbUlEREIJCgdfQWN0aW9uQgcK",
          "BV9QYXRoQggKBl9Ub2tlbkIHCgVfU2lnbkIGCgRfU0lEQgUKA19JUEIMCgpf",
          "VXNlckFnZW50QgwKCl9Ub2tlblR5cGVCDAoKX1RpbWVTdGFtcEILCglfTGFu",
          "Z3VhZ2VCDQoLX0FQSVZlcnNpb25CCQoHX01ldGhvZEIGCgRfVUlEQgoKCF9J",
          "c0FkbWluQg0KC19TZXNzaW9uRW5kQgwKCl9Db21wbGV0ZWRCCwoJX1JlYWRv",
          "bmx5QgcKBV9GaWxlQgsKCV9GaWxlbmFtZUIFCgNfSVIi3gEKD0ludGVybmFs",
          "UmVxdWVzdBISCgVQYXJhbRgBIAEoCUgAiAEBEhQKB1BhcmFtSUQYAiABKAlI",
          "AYgBARITCgZNZXRob2QYAyABKAlIAogBARIoCgRBcmdzGAQgAygLMhouSW50",
          "ZXJuYWxSZXF1ZXN0LkFyZ3NFbnRyeRpBCglBcmdzRW50cnkSCwoDa2V5GAEg",
          "ASgJEiMKBXZhbHVlGAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueToCOAFC",
          "CAoGX1BhcmFtQgoKCF9QYXJhbUlEQgkKB19NZXRob2QicwoFRXJyb3ISDAoE",
          "Y29kZRgBIAEoBRIPCgdtZXNzYWdlGAIgASgJEh4KBG1ldGEYAyADKAsyEC5F",
          "cnJvci5NZXRhRW50cnkaKwoJTWV0YUVudHJ5EgsKA2tleRgBIAEoCRINCgV2",
          "YWx1ZRgCIAEoCToCOAEi+QEKCFJlc3BvbnNlEiEKBERhdGEYASADKAsyEy5S",
          "ZXNwb25zZS5EYXRhRW50cnkSIgoLUmVxdWVzdEJhY2sYAiABKAsyCC5SZXF1",
          "ZXN0SACIAQESJAoEQ29kZRgDIAEoDjIRLlVwbG9hZFN0YXR1c0NvZGVIAYgB",
          "ARIaCgVlcnJvchgEIAEoCzIGLkVycm9ySAKIAQEaQQoJRGF0YUVudHJ5EgsK",
          "A2tleRgBIAEoCRIjCgV2YWx1ZRgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5B",
          "bnk6AjgBQg4KDF9SZXF1ZXN0QmFja0IHCgVfQ29kZUIICgZfZXJyb3IiJwoJ",
          "RmlsZUNodW5rEgwKBG5hbWUYASABKAkSDAoEZGF0YRgCIAEoDCJlCglTdHJp",
          "bmdNYXASKAoHZW50cmllcxgBIAMoCzIXLlN0cmluZ01hcC5FbnRyaWVzRW50",
          "cnkaLgoMRW50cmllc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEo",
          "CToCOAEqMwoQVXBsb2FkU3RhdHVzQ29kZRILCgdVbmtub3duEAASBgoCT2sQ",
          "ARIKCgZGYWlsZWQQAjJHCgdSZXZlcnNlEhkKAkRvEgguUmVxdWVzdBoJLlJl",
          "c3BvbnNlEiEKBlN0cmVhbRIILlJlcXVlc3QaCS5SZXNwb25zZSgBMAFCBFoC",
          "Li9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::UploadStatusCode), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Module", "Param", "ParamID", "ParamIDD", "Action", "Args", "Path", "Token", "Sign", "SID", "IP", "UserAgent", "TokenType", "TimeStamp", "Language", "APIVersion", "Method", "UID", "IsAdmin", "SessionEnd", "Completed", "Readonly", "File", "Filename", "Files", "IR" }, new[]{ "Module", "Param", "ParamID", "ParamIDD", "Action", "Path", "Token", "Sign", "SID", "IP", "UserAgent", "TokenType", "TimeStamp", "Language", "APIVersion", "Method", "UID", "IsAdmin", "SessionEnd", "Completed", "Readonly", "File", "Filename", "IR" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::InternalRequest), global::InternalRequest.Parser, new[]{ "Param", "ParamID", "Method", "Args" }, new[]{ "Param", "ParamID", "Method" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::Error), global::Error.Parser, new[]{ "Code", "Message", "Meta" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Data", "RequestBack", "Code", "Error" }, new[]{ "RequestBack", "Code", "Error" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::FileChunk), global::FileChunk.Parser, new[]{ "Name", "Data" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::StringMap), global::StringMap.Parser, new[]{ "Entries" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// -------------------
/// Upload status
/// -------------------
/// </summary>
public enum UploadStatusCode {
  [pbr::OriginalName("Unknown")] Unknown = 0,
  [pbr::OriginalName("Ok")] Ok = 1,
  [pbr::OriginalName("Failed")] Failed = 2,
}

#endregion

#region Messages
/// <summary>
/// -------------------
/// Client → Server
/// -------------------
/// </summary>
public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MicroserviceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request(Request other) : this() {
    _hasBits0 = other._hasBits0;
    module_ = other.module_;
    param_ = other.param_;
    paramID_ = other.paramID_;
    paramIDD_ = other.paramIDD_;
    action_ = other.action_;
    args_ = other.args_.Clone();
    path_ = other.path_;
    token_ = other.token_;
    sign_ = other.sign_;
    sID_ = other.sID_;
    iP_ = other.iP_;
    userAgent_ = other.userAgent_;
    tokenType_ = other.tokenType_;
    timeStamp_ = other.timeStamp_;
    language_ = other.language_;
    aPIVersion_ = other.aPIVersion_;
    method_ = other.method_;
    uID_ = other.uID_;
    isAdmin_ = other.isAdmin_;
    sessionEnd_ = other.sessionEnd_;
    completed_ = other.completed_;
    readonly_ = other.readonly_;
    file_ = other.file_;
    filename_ = other.filename_;
    files_ = other.files_.Clone();
    iR_ = other.iR_ != null ? other.iR_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "Module" field.</summary>
  public const int ModuleFieldNumber = 1;
  private string module_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Module {
    get { return module_ ?? ""; }
    set {
      module_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Module" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasModule {
    get { return module_ != null; }
  }
  /// <summary>Clears the value of the "Module" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearModule() {
    module_ = null;
  }

  /// <summary>Field number for the "Param" field.</summary>
  public const int ParamFieldNumber = 2;
  private string param_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Param {
    get { return param_ ?? ""; }
    set {
      param_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Param" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasParam {
    get { return param_ != null; }
  }
  /// <summary>Clears the value of the "Param" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearParam() {
    param_ = null;
  }

  /// <summary>Field number for the "ParamID" field.</summary>
  public const int ParamIDFieldNumber = 3;
  private string paramID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ParamID {
    get { return paramID_ ?? ""; }
    set {
      paramID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "ParamID" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasParamID {
    get { return paramID_ != null; }
  }
  /// <summary>Clears the value of the "ParamID" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearParamID() {
    paramID_ = null;
  }

  /// <summary>Field number for the "ParamIDD" field.</summary>
  public const int ParamIDDFieldNumber = 4;
  private string paramIDD_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ParamIDD {
    get { return paramIDD_ ?? ""; }
    set {
      paramIDD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "ParamIDD" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasParamIDD {
    get { return paramIDD_ != null; }
  }
  /// <summary>Clears the value of the "ParamIDD" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearParamIDD() {
    paramIDD_ = null;
  }

  /// <summary>Field number for the "Action" field.</summary>
  public const int ActionFieldNumber = 5;
  private string action_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Action {
    get { return action_ ?? ""; }
    set {
      action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Action" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAction {
    get { return action_ != null; }
  }
  /// <summary>Clears the value of the "Action" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAction() {
    action_ = null;
  }

  /// <summary>Field number for the "Args" field.</summary>
  public const int ArgsFieldNumber = 6;
  private static readonly pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>.Codec _map_args_codec
      = new pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Google.Protobuf.WellKnownTypes.Any.Parser), 50);
  private readonly pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any> args_ = new pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any> Args {
    get { return args_; }
  }

  /// <summary>Field number for the "Path" field.</summary>
  public const int PathFieldNumber = 7;
  private string path_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Path {
    get { return path_ ?? ""; }
    set {
      path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Path" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPath {
    get { return path_ != null; }
  }
  /// <summary>Clears the value of the "Path" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPath() {
    path_ = null;
  }

  /// <summary>Field number for the "Token" field.</summary>
  public const int TokenFieldNumber = 8;
  private string token_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Token {
    get { return token_ ?? ""; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Token" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasToken {
    get { return token_ != null; }
  }
  /// <summary>Clears the value of the "Token" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearToken() {
    token_ = null;
  }

  /// <summary>Field number for the "Sign" field.</summary>
  public const int SignFieldNumber = 9;
  private string sign_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Sign {
    get { return sign_ ?? ""; }
    set {
      sign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Sign" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSign {
    get { return sign_ != null; }
  }
  /// <summary>Clears the value of the "Sign" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSign() {
    sign_ = null;
  }

  /// <summary>Field number for the "SID" field.</summary>
  public const int SIDFieldNumber = 10;
  private string sID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SID {
    get { return sID_ ?? ""; }
    set {
      sID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "SID" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSID {
    get { return sID_ != null; }
  }
  /// <summary>Clears the value of the "SID" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSID() {
    sID_ = null;
  }

  /// <summary>Field number for the "IP" field.</summary>
  public const int IPFieldNumber = 11;
  private string iP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string IP {
    get { return iP_ ?? ""; }
    set {
      iP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "IP" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasIP {
    get { return iP_ != null; }
  }
  /// <summary>Clears the value of the "IP" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearIP() {
    iP_ = null;
  }

  /// <summary>Field number for the "UserAgent" field.</summary>
  public const int UserAgentFieldNumber = 12;
  private string userAgent_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserAgent {
    get { return userAgent_ ?? ""; }
    set {
      userAgent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "UserAgent" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUserAgent {
    get { return userAgent_ != null; }
  }
  /// <summary>Clears the value of the "UserAgent" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUserAgent() {
    userAgent_ = null;
  }

  /// <summary>Field number for the "TokenType" field.</summary>
  public const int TokenTypeFieldNumber = 13;
  private string tokenType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TokenType {
    get { return tokenType_ ?? ""; }
    set {
      tokenType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "TokenType" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTokenType {
    get { return tokenType_ != null; }
  }
  /// <summary>Clears the value of the "TokenType" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTokenType() {
    tokenType_ = null;
  }

  /// <summary>Field number for the "TimeStamp" field.</summary>
  public const int TimeStampFieldNumber = 14;
  private int timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TimeStamp {
    get { if ((_hasBits0 & 1) != 0) { return timeStamp_; } else { return 0; } }
    set {
      _hasBits0 |= 1;
      timeStamp_ = value;
    }
  }
  /// <summary>Gets whether the "TimeStamp" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTimeStamp {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "TimeStamp" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTimeStamp() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "Language" field.</summary>
  public const int LanguageFieldNumber = 15;
  private string language_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Language {
    get { return language_ ?? ""; }
    set {
      language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Language" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasLanguage {
    get { return language_ != null; }
  }
  /// <summary>Clears the value of the "Language" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearLanguage() {
    language_ = null;
  }

  /// <summary>Field number for the "APIVersion" field.</summary>
  public const int APIVersionFieldNumber = 16;
  private string aPIVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string APIVersion {
    get { return aPIVersion_ ?? ""; }
    set {
      aPIVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "APIVersion" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAPIVersion {
    get { return aPIVersion_ != null; }
  }
  /// <summary>Clears the value of the "APIVersion" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAPIVersion() {
    aPIVersion_ = null;
  }

  /// <summary>Field number for the "Method" field.</summary>
  public const int MethodFieldNumber = 17;
  private string method_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Method {
    get { return method_ ?? ""; }
    set {
      method_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Method" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasMethod {
    get { return method_ != null; }
  }
  /// <summary>Clears the value of the "Method" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMethod() {
    method_ = null;
  }

  /// <summary>Field number for the "UID" field.</summary>
  public const int UIDFieldNumber = 18;
  private string uID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UID {
    get { return uID_ ?? ""; }
    set {
      uID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "UID" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUID {
    get { return uID_ != null; }
  }
  /// <summary>Clears the value of the "UID" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUID() {
    uID_ = null;
  }

  /// <summary>Field number for the "IsAdmin" field.</summary>
  public const int IsAdminFieldNumber = 19;
  private int isAdmin_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsAdmin {
    get { if ((_hasBits0 & 2) != 0) { return isAdmin_; } else { return 0; } }
    set {
      _hasBits0 |= 2;
      isAdmin_ = value;
    }
  }
  /// <summary>Gets whether the "IsAdmin" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasIsAdmin {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "IsAdmin" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearIsAdmin() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "SessionEnd" field.</summary>
  public const int SessionEndFieldNumber = 20;
  private int sessionEnd_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SessionEnd {
    get { if ((_hasBits0 & 4) != 0) { return sessionEnd_; } else { return 0; } }
    set {
      _hasBits0 |= 4;
      sessionEnd_ = value;
    }
  }
  /// <summary>Gets whether the "SessionEnd" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSessionEnd {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "SessionEnd" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSessionEnd() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "Completed" field.</summary>
  public const int CompletedFieldNumber = 21;
  private int completed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Completed {
    get { if ((_hasBits0 & 8) != 0) { return completed_; } else { return 0; } }
    set {
      _hasBits0 |= 8;
      completed_ = value;
    }
  }
  /// <summary>Gets whether the "Completed" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCompleted {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "Completed" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCompleted() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "Readonly" field.</summary>
  public const int ReadonlyFieldNumber = 22;
  private int readonly_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Readonly {
    get { if ((_hasBits0 & 16) != 0) { return readonly_; } else { return 0; } }
    set {
      _hasBits0 |= 16;
      readonly_ = value;
    }
  }
  /// <summary>Gets whether the "Readonly" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasReadonly {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "Readonly" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearReadonly() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "File" field.</summary>
  public const int FileFieldNumber = 23;
  private pb::ByteString file_;
  /// <summary>
  /// Single file upload
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString File {
    get { return file_ ?? pb::ByteString.Empty; }
    set {
      file_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "File" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFile {
    get { return file_ != null; }
  }
  /// <summary>Clears the value of the "File" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFile() {
    file_ = null;
  }

  /// <summary>Field number for the "Filename" field.</summary>
  public const int FilenameFieldNumber = 24;
  private string filename_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Filename {
    get { return filename_ ?? ""; }
    set {
      filename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Filename" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFilename {
    get { return filename_ != null; }
  }
  /// <summary>Clears the value of the "Filename" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFilename() {
    filename_ = null;
  }

  /// <summary>Field number for the "Files" field.</summary>
  public const int FilesFieldNumber = 25;
  private static readonly pb::FieldCodec<string> _repeated_files_codec
      = pb::FieldCodec.ForString(202);
  private readonly pbc::RepeatedField<string> files_ = new pbc::RepeatedField<string>();
  /// <summary>
  /// Multi-file upload (list of filenames)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> Files {
    get { return files_; }
  }

  /// <summary>Field number for the "IR" field.</summary>
  public const int IRFieldNumber = 26;
  private global::InternalRequest iR_;
  /// <summary>
  /// Optional: internal request (used by gateway)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::InternalRequest IR {
    get { return iR_; }
    set {
      iR_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Module != other.Module) return false;
    if (Param != other.Param) return false;
    if (ParamID != other.ParamID) return false;
    if (ParamIDD != other.ParamIDD) return false;
    if (Action != other.Action) return false;
    if (!Args.Equals(other.Args)) return false;
    if (Path != other.Path) return false;
    if (Token != other.Token) return false;
    if (Sign != other.Sign) return false;
    if (SID != other.SID) return false;
    if (IP != other.IP) return false;
    if (UserAgent != other.UserAgent) return false;
    if (TokenType != other.TokenType) return false;
    if (TimeStamp != other.TimeStamp) return false;
    if (Language != other.Language) return false;
    if (APIVersion != other.APIVersion) return false;
    if (Method != other.Method) return false;
    if (UID != other.UID) return false;
    if (IsAdmin != other.IsAdmin) return false;
    if (SessionEnd != other.SessionEnd) return false;
    if (Completed != other.Completed) return false;
    if (Readonly != other.Readonly) return false;
    if (File != other.File) return false;
    if (Filename != other.Filename) return false;
    if(!files_.Equals(other.files_)) return false;
    if (!object.Equals(IR, other.IR)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasModule) hash ^= Module.GetHashCode();
    if (HasParam) hash ^= Param.GetHashCode();
    if (HasParamID) hash ^= ParamID.GetHashCode();
    if (HasParamIDD) hash ^= ParamIDD.GetHashCode();
    if (HasAction) hash ^= Action.GetHashCode();
    hash ^= Args.GetHashCode();
    if (HasPath) hash ^= Path.GetHashCode();
    if (HasToken) hash ^= Token.GetHashCode();
    if (HasSign) hash ^= Sign.GetHashCode();
    if (HasSID) hash ^= SID.GetHashCode();
    if (HasIP) hash ^= IP.GetHashCode();
    if (HasUserAgent) hash ^= UserAgent.GetHashCode();
    if (HasTokenType) hash ^= TokenType.GetHashCode();
    if (HasTimeStamp) hash ^= TimeStamp.GetHashCode();
    if (HasLanguage) hash ^= Language.GetHashCode();
    if (HasAPIVersion) hash ^= APIVersion.GetHashCode();
    if (HasMethod) hash ^= Method.GetHashCode();
    if (HasUID) hash ^= UID.GetHashCode();
    if (HasIsAdmin) hash ^= IsAdmin.GetHashCode();
    if (HasSessionEnd) hash ^= SessionEnd.GetHashCode();
    if (HasCompleted) hash ^= Completed.GetHashCode();
    if (HasReadonly) hash ^= Readonly.GetHashCode();
    if (HasFile) hash ^= File.GetHashCode();
    if (HasFilename) hash ^= Filename.GetHashCode();
    hash ^= files_.GetHashCode();
    if (iR_ != null) hash ^= IR.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasModule) {
      output.WriteRawTag(10);
      output.WriteString(Module);
    }
    if (HasParam) {
      output.WriteRawTag(18);
      output.WriteString(Param);
    }
    if (HasParamID) {
      output.WriteRawTag(26);
      output.WriteString(ParamID);
    }
    if (HasParamIDD) {
      output.WriteRawTag(34);
      output.WriteString(ParamIDD);
    }
    if (HasAction) {
      output.WriteRawTag(42);
      output.WriteString(Action);
    }
    args_.WriteTo(output, _map_args_codec);
    if (HasPath) {
      output.WriteRawTag(58);
      output.WriteString(Path);
    }
    if (HasToken) {
      output.WriteRawTag(66);
      output.WriteString(Token);
    }
    if (HasSign) {
      output.WriteRawTag(74);
      output.WriteString(Sign);
    }
    if (HasSID) {
      output.WriteRawTag(82);
      output.WriteString(SID);
    }
    if (HasIP) {
      output.WriteRawTag(90);
      output.WriteString(IP);
    }
    if (HasUserAgent) {
      output.WriteRawTag(98);
      output.WriteString(UserAgent);
    }
    if (HasTokenType) {
      output.WriteRawTag(106);
      output.WriteString(TokenType);
    }
    if (HasTimeStamp) {
      output.WriteRawTag(112);
      output.WriteInt32(TimeStamp);
    }
    if (HasLanguage) {
      output.WriteRawTag(122);
      output.WriteString(Language);
    }
    if (HasAPIVersion) {
      output.WriteRawTag(130, 1);
      output.WriteString(APIVersion);
    }
    if (HasMethod) {
      output.WriteRawTag(138, 1);
      output.WriteString(Method);
    }
    if (HasUID) {
      output.WriteRawTag(146, 1);
      output.WriteString(UID);
    }
    if (HasIsAdmin) {
      output.WriteRawTag(152, 1);
      output.WriteInt32(IsAdmin);
    }
    if (HasSessionEnd) {
      output.WriteRawTag(160, 1);
      output.WriteInt32(SessionEnd);
    }
    if (HasCompleted) {
      output.WriteRawTag(168, 1);
      output.WriteInt32(Completed);
    }
    if (HasReadonly) {
      output.WriteRawTag(176, 1);
      output.WriteInt32(Readonly);
    }
    if (HasFile) {
      output.WriteRawTag(186, 1);
      output.WriteBytes(File);
    }
    if (HasFilename) {
      output.WriteRawTag(194, 1);
      output.WriteString(Filename);
    }
    files_.WriteTo(output, _repeated_files_codec);
    if (iR_ != null) {
      output.WriteRawTag(210, 1);
      output.WriteMessage(IR);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasModule) {
      output.WriteRawTag(10);
      output.WriteString(Module);
    }
    if (HasParam) {
      output.WriteRawTag(18);
      output.WriteString(Param);
    }
    if (HasParamID) {
      output.WriteRawTag(26);
      output.WriteString(ParamID);
    }
    if (HasParamIDD) {
      output.WriteRawTag(34);
      output.WriteString(ParamIDD);
    }
    if (HasAction) {
      output.WriteRawTag(42);
      output.WriteString(Action);
    }
    args_.WriteTo(ref output, _map_args_codec);
    if (HasPath) {
      output.WriteRawTag(58);
      output.WriteString(Path);
    }
    if (HasToken) {
      output.WriteRawTag(66);
      output.WriteString(Token);
    }
    if (HasSign) {
      output.WriteRawTag(74);
      output.WriteString(Sign);
    }
    if (HasSID) {
      output.WriteRawTag(82);
      output.WriteString(SID);
    }
    if (HasIP) {
      output.WriteRawTag(90);
      output.WriteString(IP);
    }
    if (HasUserAgent) {
      output.WriteRawTag(98);
      output.WriteString(UserAgent);
    }
    if (HasTokenType) {
      output.WriteRawTag(106);
      output.WriteString(TokenType);
    }
    if (HasTimeStamp) {
      output.WriteRawTag(112);
      output.WriteInt32(TimeStamp);
    }
    if (HasLanguage) {
      output.WriteRawTag(122);
      output.WriteString(Language);
    }
    if (HasAPIVersion) {
      output.WriteRawTag(130, 1);
      output.WriteString(APIVersion);
    }
    if (HasMethod) {
      output.WriteRawTag(138, 1);
      output.WriteString(Method);
    }
    if (HasUID) {
      output.WriteRawTag(146, 1);
      output.WriteString(UID);
    }
    if (HasIsAdmin) {
      output.WriteRawTag(152, 1);
      output.WriteInt32(IsAdmin);
    }
    if (HasSessionEnd) {
      output.WriteRawTag(160, 1);
      output.WriteInt32(SessionEnd);
    }
    if (HasCompleted) {
      output.WriteRawTag(168, 1);
      output.WriteInt32(Completed);
    }
    if (HasReadonly) {
      output.WriteRawTag(176, 1);
      output.WriteInt32(Readonly);
    }
    if (HasFile) {
      output.WriteRawTag(186, 1);
      output.WriteBytes(File);
    }
    if (HasFilename) {
      output.WriteRawTag(194, 1);
      output.WriteString(Filename);
    }
    files_.WriteTo(ref output, _repeated_files_codec);
    if (iR_ != null) {
      output.WriteRawTag(210, 1);
      output.WriteMessage(IR);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasModule) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Module);
    }
    if (HasParam) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Param);
    }
    if (HasParamID) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ParamID);
    }
    if (HasParamIDD) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ParamIDD);
    }
    if (HasAction) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
    }
    size += args_.CalculateSize(_map_args_codec);
    if (HasPath) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
    }
    if (HasToken) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    if (HasSign) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Sign);
    }
    if (HasSID) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SID);
    }
    if (HasIP) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IP);
    }
    if (HasUserAgent) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserAgent);
    }
    if (HasTokenType) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TokenType);
    }
    if (HasTimeStamp) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TimeStamp);
    }
    if (HasLanguage) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Language);
    }
    if (HasAPIVersion) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(APIVersion);
    }
    if (HasMethod) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(Method);
    }
    if (HasUID) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(UID);
    }
    if (HasIsAdmin) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsAdmin);
    }
    if (HasSessionEnd) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(SessionEnd);
    }
    if (HasCompleted) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Completed);
    }
    if (HasReadonly) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Readonly);
    }
    if (HasFile) {
      size += 2 + pb::CodedOutputStream.ComputeBytesSize(File);
    }
    if (HasFilename) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(Filename);
    }
    size += files_.CalculateSize(_repeated_files_codec);
    if (iR_ != null) {
      size += 2 + pb::CodedOutputStream.ComputeMessageSize(IR);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.HasModule) {
      Module = other.Module;
    }
    if (other.HasParam) {
      Param = other.Param;
    }
    if (other.HasParamID) {
      ParamID = other.ParamID;
    }
    if (other.HasParamIDD) {
      ParamIDD = other.ParamIDD;
    }
    if (other.HasAction) {
      Action = other.Action;
    }
    args_.Add(other.args_);
    if (other.HasPath) {
      Path = other.Path;
    }
    if (other.HasToken) {
      Token = other.Token;
    }
    if (other.HasSign) {
      Sign = other.Sign;
    }
    if (other.HasSID) {
      SID = other.SID;
    }
    if (other.HasIP) {
      IP = other.IP;
    }
    if (other.HasUserAgent) {
      UserAgent = other.UserAgent;
    }
    if (other.HasTokenType) {
      TokenType = other.TokenType;
    }
    if (other.HasTimeStamp) {
      TimeStamp = other.TimeStamp;
    }
    if (other.HasLanguage) {
      Language = other.Language;
    }
    if (other.HasAPIVersion) {
      APIVersion = other.APIVersion;
    }
    if (other.HasMethod) {
      Method = other.Method;
    }
    if (other.HasUID) {
      UID = other.UID;
    }
    if (other.HasIsAdmin) {
      IsAdmin = other.IsAdmin;
    }
    if (other.HasSessionEnd) {
      SessionEnd = other.SessionEnd;
    }
    if (other.HasCompleted) {
      Completed = other.Completed;
    }
    if (other.HasReadonly) {
      Readonly = other.Readonly;
    }
    if (other.HasFile) {
      File = other.File;
    }
    if (other.HasFilename) {
      Filename = other.Filename;
    }
    files_.Add(other.files_);
    if (other.iR_ != null) {
      if (iR_ == null) {
        IR = new global::InternalRequest();
      }
      IR.MergeFrom(other.IR);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Module = input.ReadString();
          break;
        }
        case 18: {
          Param = input.ReadString();
          break;
        }
        case 26: {
          ParamID = input.ReadString();
          break;
        }
        case 34: {
          ParamIDD = input.ReadString();
          break;
        }
        case 42: {
          Action = input.ReadString();
          break;
        }
        case 50: {
          args_.AddEntriesFrom(input, _map_args_codec);
          break;
        }
        case 58: {
          Path = input.ReadString();
          break;
        }
        case 66: {
          Token = input.ReadString();
          break;
        }
        case 74: {
          Sign = input.ReadString();
          break;
        }
        case 82: {
          SID = input.ReadString();
          break;
        }
        case 90: {
          IP = input.ReadString();
          break;
        }
        case 98: {
          UserAgent = input.ReadString();
          break;
        }
        case 106: {
          TokenType = input.ReadString();
          break;
        }
        case 112: {
          TimeStamp = input.ReadInt32();
          break;
        }
        case 122: {
          Language = input.ReadString();
          break;
        }
        case 130: {
          APIVersion = input.ReadString();
          break;
        }
        case 138: {
          Method = input.ReadString();
          break;
        }
        case 146: {
          UID = input.ReadString();
          break;
        }
        case 152: {
          IsAdmin = input.ReadInt32();
          break;
        }
        case 160: {
          SessionEnd = input.ReadInt32();
          break;
        }
        case 168: {
          Completed = input.ReadInt32();
          break;
        }
        case 176: {
          Readonly = input.ReadInt32();
          break;
        }
        case 186: {
          File = input.ReadBytes();
          break;
        }
        case 194: {
          Filename = input.ReadString();
          break;
        }
        case 202: {
          files_.AddEntriesFrom(input, _repeated_files_codec);
          break;
        }
        case 210: {
          if (iR_ == null) {
            IR = new global::InternalRequest();
          }
          input.ReadMessage(IR);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Module = input.ReadString();
          break;
        }
        case 18: {
          Param = input.ReadString();
          break;
        }
        case 26: {
          ParamID = input.ReadString();
          break;
        }
        case 34: {
          ParamIDD = input.ReadString();
          break;
        }
        case 42: {
          Action = input.ReadString();
          break;
        }
        case 50: {
          args_.AddEntriesFrom(ref input, _map_args_codec);
          break;
        }
        case 58: {
          Path = input.ReadString();
          break;
        }
        case 66: {
          Token = input.ReadString();
          break;
        }
        case 74: {
          Sign = input.ReadString();
          break;
        }
        case 82: {
          SID = input.ReadString();
          break;
        }
        case 90: {
          IP = input.ReadString();
          break;
        }
        case 98: {
          UserAgent = input.ReadString();
          break;
        }
        case 106: {
          TokenType = input.ReadString();
          break;
        }
        case 112: {
          TimeStamp = input.ReadInt32();
          break;
        }
        case 122: {
          Language = input.ReadString();
          break;
        }
        case 130: {
          APIVersion = input.ReadString();
          break;
        }
        case 138: {
          Method = input.ReadString();
          break;
        }
        case 146: {
          UID = input.ReadString();
          break;
        }
        case 152: {
          IsAdmin = input.ReadInt32();
          break;
        }
        case 160: {
          SessionEnd = input.ReadInt32();
          break;
        }
        case 168: {
          Completed = input.ReadInt32();
          break;
        }
        case 176: {
          Readonly = input.ReadInt32();
          break;
        }
        case 186: {
          File = input.ReadBytes();
          break;
        }
        case 194: {
          Filename = input.ReadString();
          break;
        }
        case 202: {
          files_.AddEntriesFrom(ref input, _repeated_files_codec);
          break;
        }
        case 210: {
          if (iR_ == null) {
            IR = new global::InternalRequest();
          }
          input.ReadMessage(IR);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// -------------------
/// Internal request (used by gateway)
/// -------------------
/// </summary>
public sealed partial class InternalRequest : pb::IMessage<InternalRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InternalRequest> _parser = new pb::MessageParser<InternalRequest>(() => new InternalRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InternalRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MicroserviceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InternalRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InternalRequest(InternalRequest other) : this() {
    param_ = other.param_;
    paramID_ = other.paramID_;
    method_ = other.method_;
    args_ = other.args_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InternalRequest Clone() {
    return new InternalRequest(this);
  }

  /// <summary>Field number for the "Param" field.</summary>
  public const int ParamFieldNumber = 1;
  private string param_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Param {
    get { return param_ ?? ""; }
    set {
      param_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Param" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasParam {
    get { return param_ != null; }
  }
  /// <summary>Clears the value of the "Param" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearParam() {
    param_ = null;
  }

  /// <summary>Field number for the "ParamID" field.</summary>
  public const int ParamIDFieldNumber = 2;
  private string paramID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ParamID {
    get { return paramID_ ?? ""; }
    set {
      paramID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "ParamID" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasParamID {
    get { return paramID_ != null; }
  }
  /// <summary>Clears the value of the "ParamID" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearParamID() {
    paramID_ = null;
  }

  /// <summary>Field number for the "Method" field.</summary>
  public const int MethodFieldNumber = 3;
  private string method_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Method {
    get { return method_ ?? ""; }
    set {
      method_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "Method" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasMethod {
    get { return method_ != null; }
  }
  /// <summary>Clears the value of the "Method" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMethod() {
    method_ = null;
  }

  /// <summary>Field number for the "Args" field.</summary>
  public const int ArgsFieldNumber = 4;
  private static readonly pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>.Codec _map_args_codec
      = new pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Google.Protobuf.WellKnownTypes.Any.Parser), 34);
  private readonly pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any> args_ = new pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any> Args {
    get { return args_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InternalRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InternalRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Param != other.Param) return false;
    if (ParamID != other.ParamID) return false;
    if (Method != other.Method) return false;
    if (!Args.Equals(other.Args)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasParam) hash ^= Param.GetHashCode();
    if (HasParamID) hash ^= ParamID.GetHashCode();
    if (HasMethod) hash ^= Method.GetHashCode();
    hash ^= Args.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasParam) {
      output.WriteRawTag(10);
      output.WriteString(Param);
    }
    if (HasParamID) {
      output.WriteRawTag(18);
      output.WriteString(ParamID);
    }
    if (HasMethod) {
      output.WriteRawTag(26);
      output.WriteString(Method);
    }
    args_.WriteTo(output, _map_args_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasParam) {
      output.WriteRawTag(10);
      output.WriteString(Param);
    }
    if (HasParamID) {
      output.WriteRawTag(18);
      output.WriteString(ParamID);
    }
    if (HasMethod) {
      output.WriteRawTag(26);
      output.WriteString(Method);
    }
    args_.WriteTo(ref output, _map_args_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasParam) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Param);
    }
    if (HasParamID) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ParamID);
    }
    if (HasMethod) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Method);
    }
    size += args_.CalculateSize(_map_args_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InternalRequest other) {
    if (other == null) {
      return;
    }
    if (other.HasParam) {
      Param = other.Param;
    }
    if (other.HasParamID) {
      ParamID = other.ParamID;
    }
    if (other.HasMethod) {
      Method = other.Method;
    }
    args_.Add(other.args_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Param = input.ReadString();
          break;
        }
        case 18: {
          ParamID = input.ReadString();
          break;
        }
        case 26: {
          Method = input.ReadString();
          break;
        }
        case 34: {
          args_.AddEntriesFrom(input, _map_args_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Param = input.ReadString();
          break;
        }
        case 18: {
          ParamID = input.ReadString();
          break;
        }
        case 26: {
          Method = input.ReadString();
          break;
        }
        case 34: {
          args_.AddEntriesFrom(ref input, _map_args_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// -------------------
/// Standardized error format
/// -------------------
/// </summary>
public sealed partial class Error : pb::IMessage<Error>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Error> _parser = new pb::MessageParser<Error>(() => new Error());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Error> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MicroserviceReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Error() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Error(Error other) : this() {
    code_ = other.code_;
    message_ = other.message_;
    meta_ = other.meta_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Error Clone() {
    return new Error(this);
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 1;
  private int code_;
  /// <summary>
  /// Numeric error code
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 2;
  private string message_ = "";
  /// <summary>
  /// Human-readable message
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "meta" field.</summary>
  public const int MetaFieldNumber = 3;
  private static readonly pbc::MapField<string, string>.Codec _map_meta_codec
      = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 26);
  private readonly pbc::MapField<string, string> meta_ = new pbc::MapField<string, string>();
  /// <summary>
  /// Optional metadata (debug info, trace, etc.)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, string> Meta {
    get { return meta_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Error);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Error other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Code != other.Code) return false;
    if (Message != other.Message) return false;
    if (!Meta.Equals(other.Meta)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Code != 0) hash ^= Code.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    hash ^= Meta.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Code != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Code);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Message);
    }
    meta_.WriteTo(output, _map_meta_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Code != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Code);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Message);
    }
    meta_.WriteTo(ref output, _map_meta_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Code != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    size += meta_.CalculateSize(_map_meta_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Error other) {
    if (other == null) {
      return;
    }
    if (other.Code != 0) {
      Code = other.Code;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    meta_.Add(other.meta_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Code = input.ReadInt32();
          break;
        }
        case 18: {
          Message = input.ReadString();
          break;
        }
        case 26: {
          meta_.AddEntriesFrom(input, _map_meta_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Code = input.ReadInt32();
          break;
        }
        case 18: {
          Message = input.ReadString();
          break;
        }
        case 26: {
          meta_.AddEntriesFrom(ref input, _map_meta_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// -------------------
/// Server → Client
/// -------------------
/// </summary>
public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MicroserviceReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response(Response other) : this() {
    _hasBits0 = other._hasBits0;
    data_ = other.data_.Clone();
    requestBack_ = other.requestBack_ != null ? other.requestBack_.Clone() : null;
    code_ = other.code_;
    error_ = other.error_ != null ? other.error_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "Data" field.</summary>
  public const int DataFieldNumber = 1;
  private static readonly pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>.Codec _map_data_codec
      = new pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Google.Protobuf.WellKnownTypes.Any.Parser), 10);
  private readonly pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any> data_ = new pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any>();
  /// <summary>
  /// Main response payload
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, global::Google.Protobuf.WellKnownTypes.Any> Data {
    get { return data_; }
  }

  /// <summary>Field number for the "RequestBack" field.</summary>
  public const int RequestBackFieldNumber = 2;
  private global::Request requestBack_;
  /// <summary>
  /// Original request reference (optional)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Request RequestBack {
    get { return requestBack_; }
    set {
      requestBack_ = value;
    }
  }

  /// <summary>Field number for the "Code" field.</summary>
  public const int CodeFieldNumber = 3;
  private global::UploadStatusCode code_;
  /// <summary>
  /// Upload result (if file upload)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UploadStatusCode Code {
    get { if ((_hasBits0 & 1) != 0) { return code_; } else { return global::UploadStatusCode.Unknown; } }
    set {
      _hasBits0 |= 1;
      code_ = value;
    }
  }
  /// <summary>Gets whether the "Code" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCode {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "Code" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCode() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 4;
  private global::Error error_;
  /// <summary>
  /// Unified error object (optional)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Error Error {
    get { return error_; }
    set {
      error_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!Data.Equals(other.Data)) return false;
    if (!object.Equals(RequestBack, other.RequestBack)) return false;
    if (Code != other.Code) return false;
    if (!object.Equals(Error, other.Error)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= Data.GetHashCode();
    if (requestBack_ != null) hash ^= RequestBack.GetHashCode();
    if (HasCode) hash ^= Code.GetHashCode();
    if (error_ != null) hash ^= Error.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    data_.WriteTo(output, _map_data_codec);
    if (requestBack_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(RequestBack);
    }
    if (HasCode) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Code);
    }
    if (error_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Error);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    data_.WriteTo(ref output, _map_data_codec);
    if (requestBack_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(RequestBack);
    }
    if (HasCode) {
      output.WriteRawTag(24);
      output.WriteEnum((int) Code);
    }
    if (error_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Error);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += data_.CalculateSize(_map_data_codec);
    if (requestBack_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RequestBack);
    }
    if (HasCode) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
    }
    if (error_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    data_.Add(other.data_);
    if (other.requestBack_ != null) {
      if (requestBack_ == null) {
        RequestBack = new global::Request();
      }
      RequestBack.MergeFrom(other.RequestBack);
    }
    if (other.HasCode) {
      Code = other.Code;
    }
    if (other.error_ != null) {
      if (error_ == null) {
        Error = new global::Error();
      }
      Error.MergeFrom(other.Error);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          data_.AddEntriesFrom(input, _map_data_codec);
          break;
        }
        case 18: {
          if (requestBack_ == null) {
            RequestBack = new global::Request();
          }
          input.ReadMessage(RequestBack);
          break;
        }
        case 24: {
          Code = (global::UploadStatusCode) input.ReadEnum();
          break;
        }
        case 34: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          data_.AddEntriesFrom(ref input, _map_data_codec);
          break;
        }
        case 18: {
          if (requestBack_ == null) {
            RequestBack = new global::Request();
          }
          input.ReadMessage(RequestBack);
          break;
        }
        case 24: {
          Code = (global::UploadStatusCode) input.ReadEnum();
          break;
        }
        case 34: {
          if (error_ == null) {
            Error = new global::Error();
          }
          input.ReadMessage(Error);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// -------------------
/// Streaming data
/// -------------------
/// </summary>
public sealed partial class FileChunk : pb::IMessage<FileChunk>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FileChunk> _parser = new pb::MessageParser<FileChunk>(() => new FileChunk());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FileChunk> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MicroserviceReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FileChunk() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FileChunk(FileChunk other) : this() {
    name_ = other.name_;
    data_ = other.data_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FileChunk Clone() {
    return new FileChunk(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 2;
  private pb::ByteString data_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Data {
    get { return data_; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FileChunk);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FileChunk other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Data != other.Data) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Data.Length != 0) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Data.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Data.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Data.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FileChunk other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Data.Length != 0) {
      Data = other.Data;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Data = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Data = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// -------------------
/// Helper maps
/// -------------------
/// </summary>
public sealed partial class StringMap : pb::IMessage<StringMap>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<StringMap> _parser = new pb::MessageParser<StringMap>(() => new StringMap());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<StringMap> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MicroserviceReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StringMap() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StringMap(StringMap other) : this() {
    entries_ = other.entries_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StringMap Clone() {
    return new StringMap(this);
  }

  /// <summary>Field number for the "entries" field.</summary>
  public const int EntriesFieldNumber = 1;
  private static readonly pbc::MapField<string, string>.Codec _map_entries_codec
      = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 10);
  private readonly pbc::MapField<string, string> entries_ = new pbc::MapField<string, string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, string> Entries {
    get { return entries_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as StringMap);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(StringMap other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!Entries.Equals(other.Entries)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= Entries.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    entries_.WriteTo(output, _map_entries_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    entries_.WriteTo(ref output, _map_entries_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += entries_.CalculateSize(_map_entries_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(StringMap other) {
    if (other == null) {
      return;
    }
    entries_.Add(other.entries_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          entries_.AddEntriesFrom(input, _map_entries_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          entries_.AddEntriesFrom(ref input, _map_entries_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
