<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

namespace Gufo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gufo.AuthContext</code>
 */
class AuthContext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     * Generated from protobuf field <code>string token_type = 2;</code>
     */
    protected $token_type = '';
    /**
     * Generated from protobuf field <code>string sid = 3;</code>
     */
    protected $sid = '';
    /**
     * Generated from protobuf field <code>string uid = 4;</code>
     */
    protected $uid = '';
    /**
     * Generated from protobuf field <code>string sign = 5;</code>
     */
    protected $sign = '';
    /**
     * Generated from protobuf field <code>bool is_admin = 6;</code>
     */
    protected $is_admin = false;
    /**
     * Generated from protobuf field <code>bool readonly = 7;</code>
     */
    protected $readonly = false;
    /**
     * Generated from protobuf field <code>int64 session_end = 8;</code>
     */
    protected $session_end = 0;
    /**
     * Generated from protobuf field <code>map<string, string> meta = 9;</code>
     */
    private $meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *     @type string $token_type
     *     @type string $sid
     *     @type string $uid
     *     @type string $sign
     *     @type bool $is_admin
     *     @type bool $readonly
     *     @type int|string $session_end
     *     @type array|\Google\Protobuf\Internal\MapField $meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Microservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token_type = 2;</code>
     * @return string
     */
    public function getTokenType()
    {
        return $this->token_type;
    }

    /**
     * Generated from protobuf field <code>string token_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenType($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sid = 3;</code>
     * @return string
     */
    public function getSid()
    {
        return $this->sid;
    }

    /**
     * Generated from protobuf field <code>string sid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSid($var)
    {
        GPBUtil::checkString($var, True);
        $this->sid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uid = 4;</code>
     * @return string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>string uid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sign = 5;</code>
     * @return string
     */
    public function getSign()
    {
        return $this->sign;
    }

    /**
     * Generated from protobuf field <code>string sign = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->sign = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_admin = 6;</code>
     * @return bool
     */
    public function getIsAdmin()
    {
        return $this->is_admin;
    }

    /**
     * Generated from protobuf field <code>bool is_admin = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAdmin($var)
    {
        GPBUtil::checkBool($var);
        $this->is_admin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool readonly = 7;</code>
     * @return bool
     */
    public function getReadonly()
    {
        return $this->readonly;
    }

    /**
     * Generated from protobuf field <code>bool readonly = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setReadonly($var)
    {
        GPBUtil::checkBool($var);
        $this->readonly = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 session_end = 8;</code>
     * @return int|string
     */
    public function getSessionEnd()
    {
        return $this->session_end;
    }

    /**
     * Generated from protobuf field <code>int64 session_end = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionEnd($var)
    {
        GPBUtil::checkInt64($var);
        $this->session_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> meta = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> meta = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->meta = $arr;

        return $this;
    }

}

