<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

namespace Gufo;

use UnexpectedValueException;

/**
 * Protobuf type <code>gufo.Method</code>
 */
class Method
{
    /**
     * Generated from protobuf enum <code>METHOD_UNSPECIFIED = 0;</code>
     */
    const METHOD_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>METHOD_GET = 1;</code>
     */
    const METHOD_GET = 1;
    /**
     * Generated from protobuf enum <code>METHOD_POST = 2;</code>
     */
    const METHOD_POST = 2;
    /**
     * Generated from protobuf enum <code>METHOD_PUT = 3;</code>
     */
    const METHOD_PUT = 3;
    /**
     * Generated from protobuf enum <code>METHOD_PATCH = 4;</code>
     */
    const METHOD_PATCH = 4;
    /**
     * Generated from protobuf enum <code>METHOD_DELETE = 5;</code>
     */
    const METHOD_DELETE = 5;

    private static $valueToName = [
        self::METHOD_UNSPECIFIED => 'METHOD_UNSPECIFIED',
        self::METHOD_GET => 'METHOD_GET',
        self::METHOD_POST => 'METHOD_POST',
        self::METHOD_PUT => 'METHOD_PUT',
        self::METHOD_PATCH => 'METHOD_PATCH',
        self::METHOD_DELETE => 'METHOD_DELETE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

