<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

namespace Gufo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gufo.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Microservice name
     *
     * Generated from protobuf field <code>string module = 1;</code>
     */
    protected $module = '';
    /**
     * Resource / handler
     *
     * Generated from protobuf field <code>string param = 2;</code>
     */
    protected $param = '';
    /**
     * Primary identifier
     *
     * Generated from protobuf field <code>string param_id = 3;</code>
     */
    protected $param_id = '';
    /**
     * Secondary identifier
     *
     * Generated from protobuf field <code>string param_idd = 4;</code>
     */
    protected $param_idd = '';
    /**
     * Optional action
     *
     * Generated from protobuf field <code>string action = 5;</code>
     */
    protected $action = '';
    /**
     * Example: ?limit=10&search=alex
     *
     * Generated from protobuf field <code>map<string, string> query = 6;</code>
     */
    private $query;
    /**
     * Typed payload (protobuf recommended)
     *
     * Generated from protobuf field <code>.google.protobuf.Any body = 7;</code>
     */
    protected $body = null;
    /**
     * Generated from protobuf field <code>string path = 8;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>.gufo.Method method = 9;</code>
     */
    protected $method = 0;
    /**
     * Generated from protobuf field <code>.gufo.AuthContext auth = 10;</code>
     */
    protected $auth = null;
    /**
     * Generated from protobuf field <code>.gufo.RequestContext context = 11;</code>
     */
    protected $context = null;
    /**
     * Generated from protobuf field <code>.gufo.FileUpload file = 12;</code>
     */
    protected $file = null;
    /**
     * Generated from protobuf field <code>repeated .gufo.FileRef files = 13;</code>
     */
    private $files;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $module
     *           Microservice name
     *     @type string $param
     *           Resource / handler
     *     @type string $param_id
     *           Primary identifier
     *     @type string $param_idd
     *           Secondary identifier
     *     @type string $action
     *           Optional action
     *     @type array|\Google\Protobuf\Internal\MapField $query
     *           Example: ?limit=10&search=alex
     *     @type \Google\Protobuf\Any $body
     *           Typed payload (protobuf recommended)
     *     @type string $path
     *     @type int $method
     *     @type \Gufo\AuthContext $auth
     *     @type \Gufo\RequestContext $context
     *     @type \Gufo\FileUpload $file
     *     @type array<\Gufo\FileRef>|\Google\Protobuf\Internal\RepeatedField $files
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Microservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Microservice name
     *
     * Generated from protobuf field <code>string module = 1;</code>
     * @return string
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     * Microservice name
     *
     * Generated from protobuf field <code>string module = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->module = $var;

        return $this;
    }

    /**
     * Resource / handler
     *
     * Generated from protobuf field <code>string param = 2;</code>
     * @return string
     */
    public function getParam()
    {
        return $this->param;
    }

    /**
     * Resource / handler
     *
     * Generated from protobuf field <code>string param = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->param = $var;

        return $this;
    }

    /**
     * Primary identifier
     *
     * Generated from protobuf field <code>string param_id = 3;</code>
     * @return string
     */
    public function getParamId()
    {
        return $this->param_id;
    }

    /**
     * Primary identifier
     *
     * Generated from protobuf field <code>string param_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->param_id = $var;

        return $this;
    }

    /**
     * Secondary identifier
     *
     * Generated from protobuf field <code>string param_idd = 4;</code>
     * @return string
     */
    public function getParamIdd()
    {
        return $this->param_idd;
    }

    /**
     * Secondary identifier
     *
     * Generated from protobuf field <code>string param_idd = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParamIdd($var)
    {
        GPBUtil::checkString($var, True);
        $this->param_idd = $var;

        return $this;
    }

    /**
     * Optional action
     *
     * Generated from protobuf field <code>string action = 5;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Optional action
     *
     * Generated from protobuf field <code>string action = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Example: ?limit=10&search=alex
     *
     * Generated from protobuf field <code>map<string, string> query = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Example: ?limit=10&search=alex
     *
     * Generated from protobuf field <code>map<string, string> query = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setQuery($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->query = $arr;

        return $this;
    }

    /**
     * Typed payload (protobuf recommended)
     *
     * Generated from protobuf field <code>.google.protobuf.Any body = 7;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getBody()
    {
        return $this->body;
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Typed payload (protobuf recommended)
     *
     * Generated from protobuf field <code>.google.protobuf.Any body = 7;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 8;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gufo.Method method = 9;</code>
     * @return int
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>.gufo.Method method = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkEnum($var, \Gufo\Method::class);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gufo.AuthContext auth = 10;</code>
     * @return \Gufo\AuthContext|null
     */
    public function getAuth()
    {
        return $this->auth;
    }

    public function hasAuth()
    {
        return isset($this->auth);
    }

    public function clearAuth()
    {
        unset($this->auth);
    }

    /**
     * Generated from protobuf field <code>.gufo.AuthContext auth = 10;</code>
     * @param \Gufo\AuthContext $var
     * @return $this
     */
    public function setAuth($var)
    {
        GPBUtil::checkMessage($var, \Gufo\AuthContext::class);
        $this->auth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gufo.RequestContext context = 11;</code>
     * @return \Gufo\RequestContext|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.gufo.RequestContext context = 11;</code>
     * @param \Gufo\RequestContext $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Gufo\RequestContext::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gufo.FileUpload file = 12;</code>
     * @return \Gufo\FileUpload|null
     */
    public function getFile()
    {
        return $this->file;
    }

    public function hasFile()
    {
        return isset($this->file);
    }

    public function clearFile()
    {
        unset($this->file);
    }

    /**
     * Generated from protobuf field <code>.gufo.FileUpload file = 12;</code>
     * @param \Gufo\FileUpload $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkMessage($var, \Gufo\FileUpload::class);
        $this->file = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .gufo.FileRef files = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>repeated .gufo.FileRef files = 13;</code>
     * @param array<\Gufo\FileRef>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Gufo\FileRef::class);
        $this->files = $arr;

        return $this;
    }

}

