<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

namespace Gufo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gufo.RequestContext</code>
 */
class RequestContext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     */
    protected $ip = '';
    /**
     * Generated from protobuf field <code>string user_agent = 2;</code>
     */
    protected $user_agent = '';
    /**
     * Generated from protobuf field <code>string language = 3;</code>
     */
    protected $language = '';
    /**
     * Generated from protobuf field <code>string api_version = 4;</code>
     */
    protected $api_version = '';
    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>string trace_id = 6;</code>
     */
    protected $trace_id = '';
    /**
     * Generated from protobuf field <code>string request_id = 7;</code>
     */
    protected $request_id = '';
    /**
     * Generated from protobuf field <code>string caller = 8;</code>
     */
    protected $caller = '';
    /**
     * Generated from protobuf field <code>map<string, string> meta = 9;</code>
     */
    private $meta;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ip
     *     @type string $user_agent
     *     @type string $language
     *     @type string $api_version
     *     @type int|string $timestamp
     *     @type string $trace_id
     *     @type string $request_id
     *     @type string $caller
     *     @type array|\Google\Protobuf\Internal\MapField $meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Microservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 2;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string language = 3;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>string language = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string api_version = 4;</code>
     * @return string
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * Generated from protobuf field <code>string api_version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 6;</code>
     * @return string
     */
    public function getTraceId()
    {
        return $this->trace_id;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTraceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string request_id = 7;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>string request_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string caller = 8;</code>
     * @return string
     */
    public function getCaller()
    {
        return $this->caller;
    }

    /**
     * Generated from protobuf field <code>string caller = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCaller($var)
    {
        GPBUtil::checkString($var, True);
        $this->caller = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> meta = 9;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>map<string, string> meta = 9;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMeta($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->meta = $arr;

        return $this;
    }

}

