<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

namespace Gufo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gufo.ResponseMeta</code>
 */
class ResponseMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string trace_id = 2;</code>
     */
    protected $trace_id = '';
    /**
     * Generated from protobuf field <code>string request_id = 3;</code>
     */
    protected $request_id = '';
    /**
     * Generated from protobuf field <code>string node = 4;</code>
     */
    protected $node = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp ts = 5;</code>
     */
    protected $ts = null;
    /**
     * Generated from protobuf field <code>map<string, string> extra = 6;</code>
     */
    private $extra;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type string $trace_id
     *     @type string $request_id
     *     @type string $node
     *     @type \Google\Protobuf\Timestamp $ts
     *     @type array|\Google\Protobuf\Internal\MapField $extra
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Microservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 2;</code>
     * @return string
     */
    public function getTraceId()
    {
        return $this->trace_id;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTraceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string request_id = 3;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>string request_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string node = 4;</code>
     * @return string
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * Generated from protobuf field <code>string node = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkString($var, True);
        $this->node = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp ts = 5;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTs()
    {
        return $this->ts;
    }

    public function hasTs()
    {
        return isset($this->ts);
    }

    public function clearTs()
    {
        unset($this->ts);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp ts = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTs($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> extra = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>map<string, string> extra = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExtra($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->extra = $arr;

        return $this;
    }

}

