<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

namespace Gufo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gufo.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Main response payload
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> data = 1;</code>
     */
    private $data;
    /**
     * Error object
     *
     * Generated from protobuf field <code>.gufo.Error error = 2;</code>
     */
    protected $error = null;
    /**
     * Metadata
     *
     * Generated from protobuf field <code>.gufo.ResponseMeta meta = 3;</code>
     */
    protected $meta = null;
    /**
     * Upload result
     *
     * Generated from protobuf field <code>.gufo.UploadStatusCode code = 4;</code>
     */
    protected $code = 0;
    /**
     * Optional debug echo
     *
     * Generated from protobuf field <code>.gufo.Request request_back = 5;</code>
     */
    protected $request_back = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $data
     *           Main response payload
     *     @type \Gufo\Error $error
     *           Error object
     *     @type \Gufo\ResponseMeta $meta
     *           Metadata
     *     @type int $code
     *           Upload result
     *     @type \Gufo\Request $request_back
     *           Optional debug echo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Microservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Main response payload
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> data = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Main response payload
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> data = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->data = $arr;

        return $this;
    }

    /**
     * Error object
     *
     * Generated from protobuf field <code>.gufo.Error error = 2;</code>
     * @return \Gufo\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Error object
     *
     * Generated from protobuf field <code>.gufo.Error error = 2;</code>
     * @param \Gufo\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Gufo\Error::class);
        $this->error = $var;

        return $this;
    }

    /**
     * Metadata
     *
     * Generated from protobuf field <code>.gufo.ResponseMeta meta = 3;</code>
     * @return \Gufo\ResponseMeta|null
     */
    public function getMeta()
    {
        return $this->meta;
    }

    public function hasMeta()
    {
        return isset($this->meta);
    }

    public function clearMeta()
    {
        unset($this->meta);
    }

    /**
     * Metadata
     *
     * Generated from protobuf field <code>.gufo.ResponseMeta meta = 3;</code>
     * @param \Gufo\ResponseMeta $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \Gufo\ResponseMeta::class);
        $this->meta = $var;

        return $this;
    }

    /**
     * Upload result
     *
     * Generated from protobuf field <code>.gufo.UploadStatusCode code = 4;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Upload result
     *
     * Generated from protobuf field <code>.gufo.UploadStatusCode code = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkEnum($var, \Gufo\UploadStatusCode::class);
        $this->code = $var;

        return $this;
    }

    /**
     * Optional debug echo
     *
     * Generated from protobuf field <code>.gufo.Request request_back = 5;</code>
     * @return \Gufo\Request|null
     */
    public function getRequestBack()
    {
        return $this->request_back;
    }

    public function hasRequestBack()
    {
        return isset($this->request_back);
    }

    public function clearRequestBack()
    {
        unset($this->request_back);
    }

    /**
     * Optional debug echo
     *
     * Generated from protobuf field <code>.gufo.Request request_back = 5;</code>
     * @param \Gufo\Request $var
     * @return $this
     */
    public function setRequestBack($var)
    {
        GPBUtil::checkMessage($var, \Gufo\Request::class);
        $this->request_back = $var;

        return $this;
    }

}

