// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microservice.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Microservice.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(AuthContext);
GPBObjCClassDeclaration(Error);
GPBObjCClassDeclaration(FileRef);
GPBObjCClassDeclaration(FileUpload);
GPBObjCClassDeclaration(GPBAny);
GPBObjCClassDeclaration(GPBTimestamp);
GPBObjCClassDeclaration(Request);
GPBObjCClassDeclaration(RequestContext);
GPBObjCClassDeclaration(Response);
GPBObjCClassDeclaration(ResponseMeta);

#pragma mark - MicroserviceRoot

@implementation MicroserviceRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MicroserviceRoot_FileDescriptor

static GPBFileDescriptor *MicroserviceRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"gufo"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum UploadStatusCode

GPBEnumDescriptor *UploadStatusCode_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "UploadStatusUnknown\000UploadStatusOk\000Uploa"
        "dStatusFailed\000";
    static const int32_t values[] = {
        UploadStatusCode_UploadStatusUnknown,
        UploadStatusCode_UploadStatusOk,
        UploadStatusCode_UploadStatusFailed,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(UploadStatusCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:UploadStatusCode_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL UploadStatusCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case UploadStatusCode_UploadStatusUnknown:
    case UploadStatusCode_UploadStatusOk:
    case UploadStatusCode_UploadStatusFailed:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Enum Method_Enum

GPBEnumDescriptor *Method_Enum_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "MethodUnspecified\000MethodGet\000MethodPost\000M"
        "ethodPut\000MethodPatch\000MethodDelete\000";
    static const int32_t values[] = {
        Method_Enum_MethodUnspecified,
        Method_Enum_MethodGet,
        Method_Enum_MethodPost,
        Method_Enum_MethodPut,
        Method_Enum_MethodPatch,
        Method_Enum_MethodDelete,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(Method_Enum)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:Method_Enum_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL Method_Enum_IsValidValue(int32_t value__) {
  switch (value__) {
    case Method_Enum_MethodUnspecified:
    case Method_Enum_MethodGet:
    case Method_Enum_MethodPost:
    case Method_Enum_MethodPut:
    case Method_Enum_MethodPatch:
    case Method_Enum_MethodDelete:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Request

@implementation Request

@dynamic module;
@dynamic param;
@dynamic paramId;
@dynamic paramIdd;
@dynamic action;
@dynamic query, query_Count;
@dynamic hasBody, body;
@dynamic path;
@dynamic method;
@dynamic hasAuth, auth;
@dynamic hasContext, context;
@dynamic hasFile, file;
@dynamic filesArray, filesArray_Count;

typedef struct Request__storage_ {
  uint32_t _has_storage_[1];
  Method_Enum method;
  NSString *module;
  NSString *param;
  NSString *paramId;
  NSString *paramIdd;
  NSString *action;
  NSMutableDictionary *query;
  GPBAny *body;
  NSString *path;
  AuthContext *auth;
  RequestContext *context;
  FileUpload *file;
  NSMutableArray *filesArray;
} Request__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "module",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Module,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Request__storage_, module),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "param",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Param,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Request__storage_, param),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "paramId",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_ParamId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Request__storage_, paramId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "paramIdd",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_ParamIdd,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Request__storage_, paramIdd),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "action",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Action,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Request__storage_, action),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "query",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Query,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Request__storage_, query),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "body",
        .dataTypeSpecific.clazz = GPBObjCClass(GPBAny),
        .number = Request_FieldNumber_Body,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Request__storage_, body),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "path",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Path,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Request__storage_, path),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "method",
        .dataTypeSpecific.enumDescFunc = Method_Enum_EnumDescriptor,
        .number = Request_FieldNumber_Method,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(Request__storage_, method),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "auth",
        .dataTypeSpecific.clazz = GPBObjCClass(AuthContext),
        .number = Request_FieldNumber_Auth,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(Request__storage_, auth),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "context",
        .dataTypeSpecific.clazz = GPBObjCClass(RequestContext),
        .number = Request_FieldNumber_Context,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(Request__storage_, context),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "file",
        .dataTypeSpecific.clazz = GPBObjCClass(FileUpload),
        .number = Request_FieldNumber_File,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(Request__storage_, file),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "filesArray",
        .dataTypeSpecific.clazz = GPBObjCClass(FileRef),
        .number = Request_FieldNumber_FilesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Request__storage_, filesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Request class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Request__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Request_Method_RawValue(Request *message) {
  GPBDescriptor *descriptor = [Request descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Request_FieldNumber_Method];
  return GPBGetMessageRawEnumField(message, field);
}

void SetRequest_Method_RawValue(Request *message, int32_t value) {
  GPBDescriptor *descriptor = [Request descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Request_FieldNumber_Method];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - AuthContext

@implementation AuthContext

@dynamic token;
@dynamic tokenType;
@dynamic sid;
@dynamic uid;
@dynamic sign;
@dynamic isAdmin;
@dynamic readonly;
@dynamic sessionEnd;
@dynamic meta, meta_Count;

typedef struct AuthContext__storage_ {
  uint32_t _has_storage_[1];
  NSString *token;
  NSString *tokenType;
  NSString *sid;
  NSString *uid;
  NSString *sign;
  NSMutableDictionary *meta;
  int64_t sessionEnd;
} AuthContext__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "token",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_Token,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AuthContext__storage_, token),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "tokenType",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_TokenType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AuthContext__storage_, tokenType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sid",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_Sid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AuthContext__storage_, sid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "uid",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_Uid,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(AuthContext__storage_, uid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sign",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_Sign,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(AuthContext__storage_, sign),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isAdmin",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_IsAdmin,
        .hasIndex = 5,
        .offset = 6,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "readonly",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_Readonly,
        .hasIndex = 7,
        .offset = 8,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "sessionEnd",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_SessionEnd,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(AuthContext__storage_, sessionEnd),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "meta",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthContext_FieldNumber_Meta,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(AuthContext__storage_, meta),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AuthContext class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AuthContext__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RequestContext

@implementation RequestContext

@dynamic ip;
@dynamic userAgent;
@dynamic language;
@dynamic apiVersion;
@dynamic timestamp;
@dynamic traceId;
@dynamic requestId;
@dynamic caller;
@dynamic meta, meta_Count;

typedef struct RequestContext__storage_ {
  uint32_t _has_storage_[1];
  NSString *ip;
  NSString *userAgent;
  NSString *language;
  NSString *apiVersion;
  NSString *traceId;
  NSString *requestId;
  NSString *caller;
  NSMutableDictionary *meta;
  int64_t timestamp;
} RequestContext__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "ip",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_Ip,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RequestContext__storage_, ip),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userAgent",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_UserAgent,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RequestContext__storage_, userAgent),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "language",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_Language,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RequestContext__storage_, language),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "apiVersion",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_ApiVersion,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(RequestContext__storage_, apiVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_Timestamp,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(RequestContext__storage_, timestamp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "traceId",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_TraceId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(RequestContext__storage_, traceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "requestId",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_RequestId,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(RequestContext__storage_, requestId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "caller",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_Caller,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(RequestContext__storage_, caller),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "meta",
        .dataTypeSpecific.clazz = Nil,
        .number = RequestContext_FieldNumber_Meta,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RequestContext__storage_, meta),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RequestContext class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RequestContext__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - FileUpload

@implementation FileUpload

@dynamic data_p;
@dynamic filename;
@dynamic contentType;
@dynamic size;

typedef struct FileUpload__storage_ {
  uint32_t _has_storage_[1];
  NSData *data_p;
  NSString *filename;
  NSString *contentType;
  int64_t size;
} FileUpload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "data_p",
        .dataTypeSpecific.clazz = Nil,
        .number = FileUpload_FieldNumber_Data_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FileUpload__storage_, data_p),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "filename",
        .dataTypeSpecific.clazz = Nil,
        .number = FileUpload_FieldNumber_Filename,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(FileUpload__storage_, filename),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "contentType",
        .dataTypeSpecific.clazz = Nil,
        .number = FileUpload_FieldNumber_ContentType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(FileUpload__storage_, contentType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "size",
        .dataTypeSpecific.clazz = Nil,
        .number = FileUpload_FieldNumber_Size,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(FileUpload__storage_, size),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FileUpload class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FileUpload__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - FileRef

@implementation FileRef

@dynamic name;
@dynamic uri;

typedef struct FileRef__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSString *uri;
} FileRef__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.clazz = Nil,
        .number = FileRef_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FileRef__storage_, name),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "uri",
        .dataTypeSpecific.clazz = Nil,
        .number = FileRef_FieldNumber_Uri,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(FileRef__storage_, uri),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FileRef class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FileRef__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Response

@implementation Response

@dynamic data_p, data_p_Count;
@dynamic hasError, error;
@dynamic hasMeta, meta;
@dynamic code;
@dynamic hasRequestBack, requestBack;

typedef struct Response__storage_ {
  uint32_t _has_storage_[1];
  UploadStatusCode code;
  NSMutableDictionary *data_p;
  Error *error;
  ResponseMeta *meta;
  Request *requestBack;
} Response__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "data_p",
        .dataTypeSpecific.clazz = GPBObjCClass(GPBAny),
        .number = Response_FieldNumber_Data_p,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Response__storage_, data_p),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "error",
        .dataTypeSpecific.clazz = GPBObjCClass(Error),
        .number = Response_FieldNumber_Error,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Response__storage_, error),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "meta",
        .dataTypeSpecific.clazz = GPBObjCClass(ResponseMeta),
        .number = Response_FieldNumber_Meta,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Response__storage_, meta),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "code",
        .dataTypeSpecific.enumDescFunc = UploadStatusCode_EnumDescriptor,
        .number = Response_FieldNumber_Code,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Response__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "requestBack",
        .dataTypeSpecific.clazz = GPBObjCClass(Request),
        .number = Response_FieldNumber_RequestBack,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Response__storage_, requestBack),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Response class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Response__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Response_Code_RawValue(Response *message) {
  GPBDescriptor *descriptor = [Response descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Response_FieldNumber_Code];
  return GPBGetMessageRawEnumField(message, field);
}

void SetResponse_Code_RawValue(Response *message, int32_t value) {
  GPBDescriptor *descriptor = [Response descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Response_FieldNumber_Code];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - Error

@implementation Error

@dynamic code;
@dynamic key;
@dynamic message;
@dynamic meta, meta_Count;
@dynamic retryable;

typedef struct Error__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  NSString *key;
  NSString *message;
  NSMutableDictionary *meta;
} Error__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Error__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "key",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Key,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Error__storage_, key),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "message",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Message,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Error__storage_, message),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "meta",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Meta,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Error__storage_, meta),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "retryable",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Retryable,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Error class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Error__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ResponseMeta

@implementation ResponseMeta

@dynamic status;
@dynamic traceId;
@dynamic requestId;
@dynamic node;
@dynamic hasTs, ts;
@dynamic extra, extra_Count;

typedef struct ResponseMeta__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  NSString *traceId;
  NSString *requestId;
  NSString *node;
  GPBTimestamp *ts;
  NSMutableDictionary *extra;
} ResponseMeta__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "status",
        .dataTypeSpecific.clazz = Nil,
        .number = ResponseMeta_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ResponseMeta__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "traceId",
        .dataTypeSpecific.clazz = Nil,
        .number = ResponseMeta_FieldNumber_TraceId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ResponseMeta__storage_, traceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "requestId",
        .dataTypeSpecific.clazz = Nil,
        .number = ResponseMeta_FieldNumber_RequestId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ResponseMeta__storage_, requestId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "node",
        .dataTypeSpecific.clazz = Nil,
        .number = ResponseMeta_FieldNumber_Node,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ResponseMeta__storage_, node),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ts",
        .dataTypeSpecific.clazz = GPBObjCClass(GPBTimestamp),
        .number = ResponseMeta_FieldNumber_Ts,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ResponseMeta__storage_, ts),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "extra",
        .dataTypeSpecific.clazz = Nil,
        .number = ResponseMeta_FieldNumber_Extra,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ResponseMeta__storage_, extra),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ResponseMeta class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ResponseMeta__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - FileChunk

@implementation FileChunk

@dynamic name;
@dynamic data_p;

typedef struct FileChunk__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSData *data_p;
} FileChunk__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.clazz = Nil,
        .number = FileChunk_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FileChunk__storage_, name),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "data_p",
        .dataTypeSpecific.clazz = Nil,
        .number = FileChunk_FieldNumber_Data_p,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(FileChunk__storage_, data_p),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FileChunk class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FileChunk__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
