// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microservice.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AuthContext;
@class Error;
@class FileRef;
@class FileUpload;
@class GPBAny;
@class Request;
@class RequestContext;
@class ResponseMeta;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum UploadStatusCode

typedef GPB_ENUM(UploadStatusCode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UploadStatusCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  UploadStatusCode_UploadStatusUnknown = 0,
  UploadStatusCode_UploadStatusOk = 1,
  UploadStatusCode_UploadStatusFailed = 2,
};

GPBEnumDescriptor *UploadStatusCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UploadStatusCode_IsValidValue(int32_t value);

#pragma mark - Enum Method_Enum

typedef GPB_ENUM(Method_Enum) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Method_Enum_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Method_Enum_MethodUnspecified = 0,
  Method_Enum_MethodGet = 1,
  Method_Enum_MethodPost = 2,
  Method_Enum_MethodPut = 3,
  Method_Enum_MethodPatch = 4,
  Method_Enum_MethodDelete = 5,
};

GPBEnumDescriptor *Method_Enum_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Method_Enum_IsValidValue(int32_t value);

#pragma mark - MicroserviceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MicroserviceRoot : GPBRootObject
@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_Module = 1,
  Request_FieldNumber_Param = 2,
  Request_FieldNumber_ParamId = 3,
  Request_FieldNumber_ParamIdd = 4,
  Request_FieldNumber_Action = 5,
  Request_FieldNumber_Query = 6,
  Request_FieldNumber_Body = 7,
  Request_FieldNumber_Path = 8,
  Request_FieldNumber_Method = 9,
  Request_FieldNumber_Auth = 10,
  Request_FieldNumber_Context = 11,
  Request_FieldNumber_File = 12,
  Request_FieldNumber_FilesArray = 13,
};

GPB_FINAL @interface Request : GPBMessage

/** Microservice name */
@property(nonatomic, readwrite, copy, null_resettable) NSString *module;

/** Resource / handler */
@property(nonatomic, readwrite, copy, null_resettable) NSString *param;

/** Primary identifier */
@property(nonatomic, readwrite, copy, null_resettable) NSString *paramId;

/** Secondary identifier */
@property(nonatomic, readwrite, copy, null_resettable) NSString *paramIdd;

/** Optional action */
@property(nonatomic, readwrite, copy, null_resettable) NSString *action;

/** Example: ?limit=10&search=alex */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *query;
/** The number of items in @c query without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger query_Count;

/** Typed payload (protobuf recommended) */
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite) Method_Enum method;

@property(nonatomic, readwrite, strong, null_resettable) AuthContext *auth;
/** Test to see if @c auth has been set. */
@property(nonatomic, readwrite) BOOL hasAuth;

@property(nonatomic, readwrite, strong, null_resettable) RequestContext *context;
/** Test to see if @c context has been set. */
@property(nonatomic, readwrite) BOOL hasContext;

@property(nonatomic, readwrite, strong, null_resettable) FileUpload *file;
/** Test to see if @c file has been set. */
@property(nonatomic, readwrite) BOOL hasFile;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FileRef*> *filesArray;
/** The number of items in @c filesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filesArray_Count;

@end

/**
 * Fetches the raw value of a @c Request's @c method property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Request_Method_RawValue(Request *message);
/**
 * Sets the raw value of an @c Request's @c method property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequest_Method_RawValue(Request *message, int32_t value);

#pragma mark - AuthContext

typedef GPB_ENUM(AuthContext_FieldNumber) {
  AuthContext_FieldNumber_Token = 1,
  AuthContext_FieldNumber_TokenType = 2,
  AuthContext_FieldNumber_Sid = 3,
  AuthContext_FieldNumber_Uid = 4,
  AuthContext_FieldNumber_Sign = 5,
  AuthContext_FieldNumber_IsAdmin = 6,
  AuthContext_FieldNumber_Readonly = 7,
  AuthContext_FieldNumber_SessionEnd = 8,
  AuthContext_FieldNumber_Meta = 9,
};

GPB_FINAL @interface AuthContext : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tokenType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@property(nonatomic, readwrite) BOOL isAdmin;

@property(nonatomic, readwrite) BOOL readonly;

@property(nonatomic, readwrite) int64_t sessionEnd;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *meta;
/** The number of items in @c meta without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger meta_Count;

@end

#pragma mark - RequestContext

typedef GPB_ENUM(RequestContext_FieldNumber) {
  RequestContext_FieldNumber_Ip = 1,
  RequestContext_FieldNumber_UserAgent = 2,
  RequestContext_FieldNumber_Language = 3,
  RequestContext_FieldNumber_ApiVersion = 4,
  RequestContext_FieldNumber_Timestamp = 5,
  RequestContext_FieldNumber_TraceId = 6,
  RequestContext_FieldNumber_RequestId = 7,
  RequestContext_FieldNumber_Caller = 8,
  RequestContext_FieldNumber_Meta = 9,
};

GPB_FINAL @interface RequestContext : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userAgent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;

@property(nonatomic, readwrite, copy, null_resettable) NSString *apiVersion;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *traceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *caller;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *meta;
/** The number of items in @c meta without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger meta_Count;

@end

#pragma mark - FileUpload

typedef GPB_ENUM(FileUpload_FieldNumber) {
  FileUpload_FieldNumber_Data_p = 1,
  FileUpload_FieldNumber_Filename = 2,
  FileUpload_FieldNumber_ContentType = 3,
  FileUpload_FieldNumber_Size = 4,
};

GPB_FINAL @interface FileUpload : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filename;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentType;

@property(nonatomic, readwrite) int64_t size;

@end

#pragma mark - FileRef

typedef GPB_ENUM(FileRef_FieldNumber) {
  FileRef_FieldNumber_Name = 1,
  FileRef_FieldNumber_Uri = 2,
};

GPB_FINAL @interface FileRef : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

@end

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_Data_p = 1,
  Response_FieldNumber_Error = 2,
  Response_FieldNumber_Meta = 3,
  Response_FieldNumber_Code = 4,
  Response_FieldNumber_RequestBack = 5,
};

GPB_FINAL @interface Response : GPBMessage

/** Main response payload */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, GPBAny*> *data_p;
/** The number of items in @c data_p without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger data_p_Count;

/** Error object */
@property(nonatomic, readwrite, strong, null_resettable) Error *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

/** Metadata */
@property(nonatomic, readwrite, strong, null_resettable) ResponseMeta *meta;
/** Test to see if @c meta has been set. */
@property(nonatomic, readwrite) BOOL hasMeta;

/** Upload result */
@property(nonatomic, readwrite) UploadStatusCode code;

/** Optional debug echo */
@property(nonatomic, readwrite, strong, null_resettable) Request *requestBack;
/** Test to see if @c requestBack has been set. */
@property(nonatomic, readwrite) BOOL hasRequestBack;

@end

/**
 * Fetches the raw value of a @c Response's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Response_Code_RawValue(Response *message);
/**
 * Sets the raw value of an @c Response's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponse_Code_RawValue(Response *message, int32_t value);

#pragma mark - Error

typedef GPB_ENUM(Error_FieldNumber) {
  Error_FieldNumber_Code = 1,
  Error_FieldNumber_Key = 2,
  Error_FieldNumber_Message = 3,
  Error_FieldNumber_Meta = 4,
  Error_FieldNumber_Retryable = 5,
};

GPB_FINAL @interface Error : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *meta;
/** The number of items in @c meta without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger meta_Count;

@property(nonatomic, readwrite) BOOL retryable;

@end

#pragma mark - ResponseMeta

typedef GPB_ENUM(ResponseMeta_FieldNumber) {
  ResponseMeta_FieldNumber_Status = 1,
  ResponseMeta_FieldNumber_TraceId = 2,
  ResponseMeta_FieldNumber_RequestId = 3,
  ResponseMeta_FieldNumber_Node = 4,
  ResponseMeta_FieldNumber_Ts = 5,
  ResponseMeta_FieldNumber_Extra = 6,
};

GPB_FINAL @interface ResponseMeta : GPBMessage

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *traceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *node;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *ts;
/** Test to see if @c ts has been set. */
@property(nonatomic, readwrite) BOOL hasTs;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *extra;
/** The number of items in @c extra without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extra_Count;

@end

#pragma mark - FileChunk

typedef GPB_ENUM(FileChunk_FieldNumber) {
  FileChunk_FieldNumber_Name = 1,
  FileChunk_FieldNumber_Data_p = 2,
};

GPB_FINAL @interface FileChunk : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
