// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microservice.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Error;
@class GPBAny;
@class InternalRequest;
@class Request;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum UploadStatusCode

/**
 * -------------------
 * Upload status
 * -------------------
 **/
typedef GPB_ENUM(UploadStatusCode) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UploadStatusCode_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  UploadStatusCode_Unknown = 0,
  UploadStatusCode_Ok = 1,
  UploadStatusCode_Failed = 2,
};

GPBEnumDescriptor *UploadStatusCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UploadStatusCode_IsValidValue(int32_t value);

#pragma mark - MicroserviceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MicroserviceRoot : GPBRootObject
@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_Module = 1,
  Request_FieldNumber_Param = 2,
  Request_FieldNumber_ParamId = 3,
  Request_FieldNumber_ParamIdd = 4,
  Request_FieldNumber_Action = 5,
  Request_FieldNumber_Args = 6,
  Request_FieldNumber_Path = 7,
  Request_FieldNumber_Token = 8,
  Request_FieldNumber_Sign = 9,
  Request_FieldNumber_Sid = 10,
  Request_FieldNumber_Ip = 11,
  Request_FieldNumber_UserAgent = 12,
  Request_FieldNumber_TokenType = 13,
  Request_FieldNumber_TimeStamp = 14,
  Request_FieldNumber_Language = 15,
  Request_FieldNumber_Apiversion = 16,
  Request_FieldNumber_Method = 17,
  Request_FieldNumber_Uid = 18,
  Request_FieldNumber_IsAdmin = 19,
  Request_FieldNumber_SessionEnd = 20,
  Request_FieldNumber_Completed = 21,
  Request_FieldNumber_Readonly = 22,
  Request_FieldNumber_File = 23,
  Request_FieldNumber_Filename = 24,
  Request_FieldNumber_FilesArray = 25,
  Request_FieldNumber_Ir = 26,
};

/**
 * -------------------
 * Client → Server
 * -------------------
 **/
GPB_FINAL @interface Request : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *module;
/** Test to see if @c module has been set. */
@property(nonatomic, readwrite) BOOL hasModule;

@property(nonatomic, readwrite, copy, null_resettable) NSString *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paramId;
/** Test to see if @c paramId has been set. */
@property(nonatomic, readwrite) BOOL hasParamId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paramIdd;
/** Test to see if @c paramIdd has been set. */
@property(nonatomic, readwrite) BOOL hasParamIdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *action;
/** Test to see if @c action has been set. */
@property(nonatomic, readwrite) BOOL hasAction;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, GPBAny*> *args;
/** The number of items in @c args without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger args_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;
/** Test to see if @c path has been set. */
@property(nonatomic, readwrite) BOOL hasPath;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;
/** Test to see if @c sign has been set. */
@property(nonatomic, readwrite) BOOL hasSign;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sid;
/** Test to see if @c sid has been set. */
@property(nonatomic, readwrite) BOOL hasSid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;
/** Test to see if @c ip has been set. */
@property(nonatomic, readwrite) BOOL hasIp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userAgent;
/** Test to see if @c userAgent has been set. */
@property(nonatomic, readwrite) BOOL hasUserAgent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tokenType;
/** Test to see if @c tokenType has been set. */
@property(nonatomic, readwrite) BOOL hasTokenType;

@property(nonatomic, readwrite) int32_t timeStamp;

@property(nonatomic, readwrite) BOOL hasTimeStamp;
@property(nonatomic, readwrite, copy, null_resettable) NSString *language;
/** Test to see if @c language has been set. */
@property(nonatomic, readwrite) BOOL hasLanguage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *apiversion;
/** Test to see if @c apiversion has been set. */
@property(nonatomic, readwrite) BOOL hasApiversion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *method;
/** Test to see if @c method has been set. */
@property(nonatomic, readwrite) BOOL hasMethod;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

@property(nonatomic, readwrite) int32_t isAdmin;

@property(nonatomic, readwrite) BOOL hasIsAdmin;
@property(nonatomic, readwrite) int32_t sessionEnd;

@property(nonatomic, readwrite) BOOL hasSessionEnd;
@property(nonatomic, readwrite) int32_t completed;

@property(nonatomic, readwrite) BOOL hasCompleted;
@property(nonatomic, readwrite) int32_t readonly;

@property(nonatomic, readwrite) BOOL hasReadonly;
/** Single file upload */
@property(nonatomic, readwrite, copy, null_resettable) NSData *file;
/** Test to see if @c file has been set. */
@property(nonatomic, readwrite) BOOL hasFile;

@property(nonatomic, readwrite, copy, null_resettable) NSString *filename;
/** Test to see if @c filename has been set. */
@property(nonatomic, readwrite) BOOL hasFilename;

/** Multi-file upload (list of filenames) */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *filesArray;
/** The number of items in @c filesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filesArray_Count;

/** Optional: internal request (used by gateway) */
@property(nonatomic, readwrite, strong, null_resettable) InternalRequest *ir;
/** Test to see if @c ir has been set. */
@property(nonatomic, readwrite) BOOL hasIr;

@end

#pragma mark - InternalRequest

typedef GPB_ENUM(InternalRequest_FieldNumber) {
  InternalRequest_FieldNumber_Param = 1,
  InternalRequest_FieldNumber_ParamId = 2,
  InternalRequest_FieldNumber_Method = 3,
  InternalRequest_FieldNumber_Args = 4,
};

/**
 * -------------------
 * Internal request (used by gateway)
 * -------------------
 **/
GPB_FINAL @interface InternalRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paramId;
/** Test to see if @c paramId has been set. */
@property(nonatomic, readwrite) BOOL hasParamId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *method;
/** Test to see if @c method has been set. */
@property(nonatomic, readwrite) BOOL hasMethod;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, GPBAny*> *args;
/** The number of items in @c args without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger args_Count;

@end

#pragma mark - Error

typedef GPB_ENUM(Error_FieldNumber) {
  Error_FieldNumber_Code = 1,
  Error_FieldNumber_Message = 2,
  Error_FieldNumber_Meta = 3,
};

/**
 * -------------------
 * Standardized error format
 * -------------------
 **/
GPB_FINAL @interface Error : GPBMessage

/** Numeric error code */
@property(nonatomic, readwrite) int32_t code;

/** Human-readable message */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** Optional metadata (debug info, trace, etc.) */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *meta;
/** The number of items in @c meta without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger meta_Count;

@end

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_Data_p = 1,
  Response_FieldNumber_RequestBack = 2,
  Response_FieldNumber_Code = 3,
  Response_FieldNumber_Error = 4,
};

/**
 * -------------------
 * Server → Client
 * -------------------
 **/
GPB_FINAL @interface Response : GPBMessage

/** Main response payload */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, GPBAny*> *data_p;
/** The number of items in @c data_p without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger data_p_Count;

/** Original request reference (optional) */
@property(nonatomic, readwrite, strong, null_resettable) Request *requestBack;
/** Test to see if @c requestBack has been set. */
@property(nonatomic, readwrite) BOOL hasRequestBack;

/** Upload result (if file upload) */
@property(nonatomic, readwrite) UploadStatusCode code;

@property(nonatomic, readwrite) BOOL hasCode;
/** Unified error object (optional) */
@property(nonatomic, readwrite, strong, null_resettable) Error *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

@end

/**
 * Fetches the raw value of a @c Response's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Response_Code_RawValue(Response *message);
/**
 * Sets the raw value of an @c Response's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponse_Code_RawValue(Response *message, int32_t value);

#pragma mark - FileChunk

typedef GPB_ENUM(FileChunk_FieldNumber) {
  FileChunk_FieldNumber_Name = 1,
  FileChunk_FieldNumber_Data_p = 2,
};

/**
 * -------------------
 * Streaming data
 * -------------------
 **/
GPB_FINAL @interface FileChunk : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - StringMap

typedef GPB_ENUM(StringMap_FieldNumber) {
  StringMap_FieldNumber_Entries = 1,
};

/**
 * -------------------
 * Helper maps
 * -------------------
 **/
GPB_FINAL @interface StringMap : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *entries;
/** The number of items in @c entries without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger entries_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
