// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microservice.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Microservice.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(Error);
GPBObjCClassDeclaration(GPBAny);
GPBObjCClassDeclaration(InternalRequest);
GPBObjCClassDeclaration(Request);
GPBObjCClassDeclaration(Response);
GPBObjCClassDeclaration(StringMap);

#pragma mark - MicroserviceRoot

@implementation MicroserviceRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MicroserviceRoot_FileDescriptor

static GPBFileDescriptor *MicroserviceRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Enum UploadStatusCode

GPBEnumDescriptor *UploadStatusCode_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Ok\000Failed\000";
    static const int32_t values[] = {
        UploadStatusCode_Unknown,
        UploadStatusCode_Ok,
        UploadStatusCode_Failed,
    };
    static const char *extraTextFormatInfo = "\003\000\007\000\001\002\000\002\006\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(UploadStatusCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:UploadStatusCode_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL UploadStatusCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case UploadStatusCode_Unknown:
    case UploadStatusCode_Ok:
    case UploadStatusCode_Failed:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Request

@implementation Request

@dynamic hasModule, module;
@dynamic hasParam, param;
@dynamic hasParamId, paramId;
@dynamic hasParamIdd, paramIdd;
@dynamic hasAction, action;
@dynamic args, args_Count;
@dynamic hasPath, path;
@dynamic hasToken, token;
@dynamic hasSign, sign;
@dynamic hasSid, sid;
@dynamic hasIp, ip;
@dynamic hasUserAgent, userAgent;
@dynamic hasTokenType, tokenType;
@dynamic hasTimeStamp, timeStamp;
@dynamic hasLanguage, language;
@dynamic hasApiversion, apiversion;
@dynamic hasMethod, method;
@dynamic hasUid, uid;
@dynamic hasIsAdmin, isAdmin;
@dynamic hasSessionEnd, sessionEnd;
@dynamic hasCompleted, completed;
@dynamic hasReadonly, readonly;
@dynamic hasFile, file;
@dynamic hasFilename, filename;
@dynamic filesArray, filesArray_Count;
@dynamic hasIr, ir;

typedef struct Request__storage_ {
  uint32_t _has_storage_[1];
  int32_t timeStamp;
  int32_t isAdmin;
  int32_t sessionEnd;
  int32_t completed;
  int32_t readonly;
  NSString *module;
  NSString *param;
  NSString *paramId;
  NSString *paramIdd;
  NSString *action;
  NSMutableDictionary *args;
  NSString *path;
  NSString *token;
  NSString *sign;
  NSString *sid;
  NSString *ip;
  NSString *userAgent;
  NSString *tokenType;
  NSString *language;
  NSString *apiversion;
  NSString *method;
  NSString *uid;
  NSData *file;
  NSString *filename;
  NSMutableArray *filesArray;
  InternalRequest *ir;
} Request__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "module",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Module,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Request__storage_, module),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "param",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Param,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Request__storage_, param),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "paramId",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_ParamId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Request__storage_, paramId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "paramIdd",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_ParamIdd,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Request__storage_, paramIdd),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "action",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Action,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Request__storage_, action),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "args",
        .dataTypeSpecific.clazz = GPBObjCClass(GPBAny),
        .number = Request_FieldNumber_Args,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Request__storage_, args),
        .flags = (GPBFieldFlags)(GPBFieldMapKeyString | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "path",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Path,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Request__storage_, path),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "token",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Token,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Request__storage_, token),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sign",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Sign,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(Request__storage_, sign),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sid",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Sid,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(Request__storage_, sid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ip",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Ip,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(Request__storage_, ip),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userAgent",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_UserAgent,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(Request__storage_, userAgent),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "tokenType",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_TokenType,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(Request__storage_, tokenType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "timeStamp",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_TimeStamp,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(Request__storage_, timeStamp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "language",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Language,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(Request__storage_, language),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "apiversion",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Apiversion,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(Request__storage_, apiversion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "method",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Method,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(Request__storage_, method),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "uid",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Uid,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(Request__storage_, uid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isAdmin",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_IsAdmin,
        .hasIndex = 17,
        .offset = (uint32_t)offsetof(Request__storage_, isAdmin),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "sessionEnd",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_SessionEnd,
        .hasIndex = 18,
        .offset = (uint32_t)offsetof(Request__storage_, sessionEnd),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "completed",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Completed,
        .hasIndex = 19,
        .offset = (uint32_t)offsetof(Request__storage_, completed),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "readonly",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Readonly,
        .hasIndex = 20,
        .offset = (uint32_t)offsetof(Request__storage_, readonly),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "file",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_File,
        .hasIndex = 21,
        .offset = (uint32_t)offsetof(Request__storage_, file),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "filename",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_Filename,
        .hasIndex = 22,
        .offset = (uint32_t)offsetof(Request__storage_, filename),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "filesArray",
        .dataTypeSpecific.clazz = Nil,
        .number = Request_FieldNumber_FilesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Request__storage_, filesArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ir",
        .dataTypeSpecific.clazz = GPBObjCClass(InternalRequest),
        .number = Request_FieldNumber_Ir,
        .hasIndex = 23,
        .offset = (uint32_t)offsetof(Request__storage_, ir),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Request class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Request__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\032\001F\000\002E\000\003FA\000\004Fb\000\005F\000\006D\000\007D\000\010E\000\tD\000\nc\000\013b\000\014I\000\r"
        "I\000\016I\000\017H\000\020d\006\000\021F\000\022c\000\023G\000\024J\000\025I\000\026H\000\027D\000\030H\000\031\000Fi"
        "les\000\032b\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - InternalRequest

@implementation InternalRequest

@dynamic hasParam, param;
@dynamic hasParamId, paramId;
@dynamic hasMethod, method;
@dynamic args, args_Count;

typedef struct InternalRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *param;
  NSString *paramId;
  NSString *method;
  NSMutableDictionary *args;
} InternalRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "param",
        .dataTypeSpecific.clazz = Nil,
        .number = InternalRequest_FieldNumber_Param,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(InternalRequest__storage_, param),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "paramId",
        .dataTypeSpecific.clazz = Nil,
        .number = InternalRequest_FieldNumber_ParamId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(InternalRequest__storage_, paramId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "method",
        .dataTypeSpecific.clazz = Nil,
        .number = InternalRequest_FieldNumber_Method,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(InternalRequest__storage_, method),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "args",
        .dataTypeSpecific.clazz = GPBObjCClass(GPBAny),
        .number = InternalRequest_FieldNumber_Args,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(InternalRequest__storage_, args),
        .flags = (GPBFieldFlags)(GPBFieldMapKeyString | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[InternalRequest class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(InternalRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001E\000\002FA\000\003F\000\004D\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Error

@implementation Error

@dynamic code;
@dynamic message;
@dynamic meta, meta_Count;

typedef struct Error__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  NSString *message;
  NSMutableDictionary *meta;
} Error__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Error__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "message",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Message,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Error__storage_, message),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "meta",
        .dataTypeSpecific.clazz = Nil,
        .number = Error_FieldNumber_Meta,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Error__storage_, meta),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Error class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Error__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Response

@implementation Response

@dynamic data_p, data_p_Count;
@dynamic hasRequestBack, requestBack;
@dynamic hasCode, code;
@dynamic hasError, error;

typedef struct Response__storage_ {
  uint32_t _has_storage_[1];
  UploadStatusCode code;
  NSMutableDictionary *data_p;
  Request *requestBack;
  Error *error;
} Response__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "data_p",
        .dataTypeSpecific.clazz = GPBObjCClass(GPBAny),
        .number = Response_FieldNumber_Data_p,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Response__storage_, data_p),
        .flags = (GPBFieldFlags)(GPBFieldMapKeyString | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "requestBack",
        .dataTypeSpecific.clazz = GPBObjCClass(Request),
        .number = Response_FieldNumber_RequestBack,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Response__storage_, requestBack),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "code",
        .dataTypeSpecific.enumDescFunc = UploadStatusCode_EnumDescriptor,
        .number = Response_FieldNumber_Code,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Response__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "error",
        .dataTypeSpecific.clazz = GPBObjCClass(Error),
        .number = Response_FieldNumber_Error,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Response__storage_, error),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Response class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Response__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\000Data\000\002K\000\003D\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Response_Code_RawValue(Response *message) {
  GPBDescriptor *descriptor = [Response descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Response_FieldNumber_Code];
  return GPBGetMessageRawEnumField(message, field);
}

void SetResponse_Code_RawValue(Response *message, int32_t value) {
  GPBDescriptor *descriptor = [Response descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Response_FieldNumber_Code];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - FileChunk

@implementation FileChunk

@dynamic name;
@dynamic data_p;

typedef struct FileChunk__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSData *data_p;
} FileChunk__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.clazz = Nil,
        .number = FileChunk_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(FileChunk__storage_, name),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "data_p",
        .dataTypeSpecific.clazz = Nil,
        .number = FileChunk_FieldNumber_Data_p,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(FileChunk__storage_, data_p),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FileChunk class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FileChunk__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - StringMap

@implementation StringMap

@dynamic entries, entries_Count;

typedef struct StringMap__storage_ {
  uint32_t _has_storage_[1];
  NSMutableDictionary *entries;
} StringMap__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "entries",
        .dataTypeSpecific.clazz = Nil,
        .number = StringMap_FieldNumber_Entries,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(StringMap__storage_, entries),
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[StringMap class]
                                     rootClass:[MicroserviceRoot class]
                                          file:MicroserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(StringMap__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
