<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * -------------------
 * Internal request (used by gateway)
 * -------------------
 *
 * Generated from protobuf message <code>InternalRequest</code>
 */
class InternalRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Param = 1;</code>
     */
    protected $Param = null;
    /**
     * Generated from protobuf field <code>optional string ParamID = 2;</code>
     */
    protected $ParamID = null;
    /**
     * Generated from protobuf field <code>optional string Method = 3;</code>
     */
    protected $Method = null;
    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> Args = 4;</code>
     */
    private $Args;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Param
     *     @type string $ParamID
     *     @type string $Method
     *     @type array|\Google\Protobuf\Internal\MapField $Args
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Microservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Param = 1;</code>
     * @return string
     */
    public function getParam()
    {
        return isset($this->Param) ? $this->Param : '';
    }

    public function hasParam()
    {
        return isset($this->Param);
    }

    public function clearParam()
    {
        unset($this->Param);
    }

    /**
     * Generated from protobuf field <code>optional string Param = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->Param = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ParamID = 2;</code>
     * @return string
     */
    public function getParamID()
    {
        return isset($this->ParamID) ? $this->ParamID : '';
    }

    public function hasParamID()
    {
        return isset($this->ParamID);
    }

    public function clearParamID()
    {
        unset($this->ParamID);
    }

    /**
     * Generated from protobuf field <code>optional string ParamID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParamID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParamID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Method = 3;</code>
     * @return string
     */
    public function getMethod()
    {
        return isset($this->Method) ? $this->Method : '';
    }

    public function hasMethod()
    {
        return isset($this->Method);
    }

    public function clearMethod()
    {
        unset($this->Method);
    }

    /**
     * Generated from protobuf field <code>optional string Method = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->Method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> Args = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getArgs()
    {
        return $this->Args;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> Args = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->Args = $arr;

        return $this;
    }

}

