<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * -------------------
 * Client → Server
 * -------------------
 *
 * Generated from protobuf message <code>Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Module = 1;</code>
     */
    protected $Module = null;
    /**
     * Generated from protobuf field <code>optional string Param = 2;</code>
     */
    protected $Param = null;
    /**
     * Generated from protobuf field <code>optional string ParamID = 3;</code>
     */
    protected $ParamID = null;
    /**
     * Generated from protobuf field <code>optional string ParamIDD = 4;</code>
     */
    protected $ParamIDD = null;
    /**
     * Generated from protobuf field <code>optional string Action = 5;</code>
     */
    protected $Action = null;
    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> Args = 6;</code>
     */
    private $Args;
    /**
     * Generated from protobuf field <code>optional string Path = 7;</code>
     */
    protected $Path = null;
    /**
     * Generated from protobuf field <code>optional string Token = 8;</code>
     */
    protected $Token = null;
    /**
     * Generated from protobuf field <code>optional string Sign = 9;</code>
     */
    protected $Sign = null;
    /**
     * Generated from protobuf field <code>optional string SID = 10;</code>
     */
    protected $SID = null;
    /**
     * Generated from protobuf field <code>optional string IP = 11;</code>
     */
    protected $IP = null;
    /**
     * Generated from protobuf field <code>optional string UserAgent = 12;</code>
     */
    protected $UserAgent = null;
    /**
     * Generated from protobuf field <code>optional string TokenType = 13;</code>
     */
    protected $TokenType = null;
    /**
     * Generated from protobuf field <code>optional int32 TimeStamp = 14;</code>
     */
    protected $TimeStamp = null;
    /**
     * Generated from protobuf field <code>optional string Language = 15;</code>
     */
    protected $Language = null;
    /**
     * Generated from protobuf field <code>optional string APIVersion = 16;</code>
     */
    protected $APIVersion = null;
    /**
     * Generated from protobuf field <code>optional string Method = 17;</code>
     */
    protected $Method = null;
    /**
     * Generated from protobuf field <code>optional string UID = 18;</code>
     */
    protected $UID = null;
    /**
     * Generated from protobuf field <code>optional int32 IsAdmin = 19;</code>
     */
    protected $IsAdmin = null;
    /**
     * Generated from protobuf field <code>optional int32 SessionEnd = 20;</code>
     */
    protected $SessionEnd = null;
    /**
     * Generated from protobuf field <code>optional int32 Completed = 21;</code>
     */
    protected $Completed = null;
    /**
     * Generated from protobuf field <code>optional int32 Readonly = 22;</code>
     */
    protected $Readonly = null;
    /**
     * Single file upload
     *
     * Generated from protobuf field <code>optional bytes File = 23;</code>
     */
    protected $File = null;
    /**
     * Generated from protobuf field <code>optional string Filename = 24;</code>
     */
    protected $Filename = null;
    /**
     * Multi-file upload (list of filenames)
     *
     * Generated from protobuf field <code>repeated string Files = 25;</code>
     */
    private $Files;
    /**
     * Optional: internal request (used by gateway)
     *
     * Generated from protobuf field <code>optional .InternalRequest IR = 26;</code>
     */
    protected $IR = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Module
     *     @type string $Param
     *     @type string $ParamID
     *     @type string $ParamIDD
     *     @type string $Action
     *     @type array|\Google\Protobuf\Internal\MapField $Args
     *     @type string $Path
     *     @type string $Token
     *     @type string $Sign
     *     @type string $SID
     *     @type string $IP
     *     @type string $UserAgent
     *     @type string $TokenType
     *     @type int $TimeStamp
     *     @type string $Language
     *     @type string $APIVersion
     *     @type string $Method
     *     @type string $UID
     *     @type int $IsAdmin
     *     @type int $SessionEnd
     *     @type int $Completed
     *     @type int $Readonly
     *     @type string $File
     *           Single file upload
     *     @type string $Filename
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $Files
     *           Multi-file upload (list of filenames)
     *     @type \InternalRequest $IR
     *           Optional: internal request (used by gateway)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Microservice::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Module = 1;</code>
     * @return string
     */
    public function getModule()
    {
        return isset($this->Module) ? $this->Module : '';
    }

    public function hasModule()
    {
        return isset($this->Module);
    }

    public function clearModule()
    {
        unset($this->Module);
    }

    /**
     * Generated from protobuf field <code>optional string Module = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->Module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Param = 2;</code>
     * @return string
     */
    public function getParam()
    {
        return isset($this->Param) ? $this->Param : '';
    }

    public function hasParam()
    {
        return isset($this->Param);
    }

    public function clearParam()
    {
        unset($this->Param);
    }

    /**
     * Generated from protobuf field <code>optional string Param = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->Param = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ParamID = 3;</code>
     * @return string
     */
    public function getParamID()
    {
        return isset($this->ParamID) ? $this->ParamID : '';
    }

    public function hasParamID()
    {
        return isset($this->ParamID);
    }

    public function clearParamID()
    {
        unset($this->ParamID);
    }

    /**
     * Generated from protobuf field <code>optional string ParamID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParamID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParamID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ParamIDD = 4;</code>
     * @return string
     */
    public function getParamIDD()
    {
        return isset($this->ParamIDD) ? $this->ParamIDD : '';
    }

    public function hasParamIDD()
    {
        return isset($this->ParamIDD);
    }

    public function clearParamIDD()
    {
        unset($this->ParamIDD);
    }

    /**
     * Generated from protobuf field <code>optional string ParamIDD = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParamIDD($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParamIDD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Action = 5;</code>
     * @return string
     */
    public function getAction()
    {
        return isset($this->Action) ? $this->Action : '';
    }

    public function hasAction()
    {
        return isset($this->Action);
    }

    public function clearAction()
    {
        unset($this->Action);
    }

    /**
     * Generated from protobuf field <code>optional string Action = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->Action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> Args = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getArgs()
    {
        return $this->Args;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> Args = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setArgs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->Args = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Path = 7;</code>
     * @return string
     */
    public function getPath()
    {
        return isset($this->Path) ? $this->Path : '';
    }

    public function hasPath()
    {
        return isset($this->Path);
    }

    public function clearPath()
    {
        unset($this->Path);
    }

    /**
     * Generated from protobuf field <code>optional string Path = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->Path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Token = 8;</code>
     * @return string
     */
    public function getToken()
    {
        return isset($this->Token) ? $this->Token : '';
    }

    public function hasToken()
    {
        return isset($this->Token);
    }

    public function clearToken()
    {
        unset($this->Token);
    }

    /**
     * Generated from protobuf field <code>optional string Token = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->Token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Sign = 9;</code>
     * @return string
     */
    public function getSign()
    {
        return isset($this->Sign) ? $this->Sign : '';
    }

    public function hasSign()
    {
        return isset($this->Sign);
    }

    public function clearSign()
    {
        unset($this->Sign);
    }

    /**
     * Generated from protobuf field <code>optional string Sign = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->Sign = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string SID = 10;</code>
     * @return string
     */
    public function getSID()
    {
        return isset($this->SID) ? $this->SID : '';
    }

    public function hasSID()
    {
        return isset($this->SID);
    }

    public function clearSID()
    {
        unset($this->SID);
    }

    /**
     * Generated from protobuf field <code>optional string SID = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSID($var)
    {
        GPBUtil::checkString($var, True);
        $this->SID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string IP = 11;</code>
     * @return string
     */
    public function getIP()
    {
        return isset($this->IP) ? $this->IP : '';
    }

    public function hasIP()
    {
        return isset($this->IP);
    }

    public function clearIP()
    {
        unset($this->IP);
    }

    /**
     * Generated from protobuf field <code>optional string IP = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setIP($var)
    {
        GPBUtil::checkString($var, True);
        $this->IP = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string UserAgent = 12;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return isset($this->UserAgent) ? $this->UserAgent : '';
    }

    public function hasUserAgent()
    {
        return isset($this->UserAgent);
    }

    public function clearUserAgent()
    {
        unset($this->UserAgent);
    }

    /**
     * Generated from protobuf field <code>optional string UserAgent = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserAgent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string TokenType = 13;</code>
     * @return string
     */
    public function getTokenType()
    {
        return isset($this->TokenType) ? $this->TokenType : '';
    }

    public function hasTokenType()
    {
        return isset($this->TokenType);
    }

    public function clearTokenType()
    {
        unset($this->TokenType);
    }

    /**
     * Generated from protobuf field <code>optional string TokenType = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenType($var)
    {
        GPBUtil::checkString($var, True);
        $this->TokenType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 TimeStamp = 14;</code>
     * @return int
     */
    public function getTimeStamp()
    {
        return isset($this->TimeStamp) ? $this->TimeStamp : 0;
    }

    public function hasTimeStamp()
    {
        return isset($this->TimeStamp);
    }

    public function clearTimeStamp()
    {
        unset($this->TimeStamp);
    }

    /**
     * Generated from protobuf field <code>optional int32 TimeStamp = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeStamp($var)
    {
        GPBUtil::checkInt32($var);
        $this->TimeStamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Language = 15;</code>
     * @return string
     */
    public function getLanguage()
    {
        return isset($this->Language) ? $this->Language : '';
    }

    public function hasLanguage()
    {
        return isset($this->Language);
    }

    public function clearLanguage()
    {
        unset($this->Language);
    }

    /**
     * Generated from protobuf field <code>optional string Language = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string APIVersion = 16;</code>
     * @return string
     */
    public function getAPIVersion()
    {
        return isset($this->APIVersion) ? $this->APIVersion : '';
    }

    public function hasAPIVersion()
    {
        return isset($this->APIVersion);
    }

    public function clearAPIVersion()
    {
        unset($this->APIVersion);
    }

    /**
     * Generated from protobuf field <code>optional string APIVersion = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setAPIVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->APIVersion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Method = 17;</code>
     * @return string
     */
    public function getMethod()
    {
        return isset($this->Method) ? $this->Method : '';
    }

    public function hasMethod()
    {
        return isset($this->Method);
    }

    public function clearMethod()
    {
        unset($this->Method);
    }

    /**
     * Generated from protobuf field <code>optional string Method = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->Method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string UID = 18;</code>
     * @return string
     */
    public function getUID()
    {
        return isset($this->UID) ? $this->UID : '';
    }

    public function hasUID()
    {
        return isset($this->UID);
    }

    public function clearUID()
    {
        unset($this->UID);
    }

    /**
     * Generated from protobuf field <code>optional string UID = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->UID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 IsAdmin = 19;</code>
     * @return int
     */
    public function getIsAdmin()
    {
        return isset($this->IsAdmin) ? $this->IsAdmin : 0;
    }

    public function hasIsAdmin()
    {
        return isset($this->IsAdmin);
    }

    public function clearIsAdmin()
    {
        unset($this->IsAdmin);
    }

    /**
     * Generated from protobuf field <code>optional int32 IsAdmin = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setIsAdmin($var)
    {
        GPBUtil::checkInt32($var);
        $this->IsAdmin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 SessionEnd = 20;</code>
     * @return int
     */
    public function getSessionEnd()
    {
        return isset($this->SessionEnd) ? $this->SessionEnd : 0;
    }

    public function hasSessionEnd()
    {
        return isset($this->SessionEnd);
    }

    public function clearSessionEnd()
    {
        unset($this->SessionEnd);
    }

    /**
     * Generated from protobuf field <code>optional int32 SessionEnd = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setSessionEnd($var)
    {
        GPBUtil::checkInt32($var);
        $this->SessionEnd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 Completed = 21;</code>
     * @return int
     */
    public function getCompleted()
    {
        return isset($this->Completed) ? $this->Completed : 0;
    }

    public function hasCompleted()
    {
        return isset($this->Completed);
    }

    public function clearCompleted()
    {
        unset($this->Completed);
    }

    /**
     * Generated from protobuf field <code>optional int32 Completed = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setCompleted($var)
    {
        GPBUtil::checkInt32($var);
        $this->Completed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 Readonly = 22;</code>
     * @return int
     */
    public function getReadonly()
    {
        return isset($this->Readonly) ? $this->Readonly : 0;
    }

    public function hasReadonly()
    {
        return isset($this->Readonly);
    }

    public function clearReadonly()
    {
        unset($this->Readonly);
    }

    /**
     * Generated from protobuf field <code>optional int32 Readonly = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setReadonly($var)
    {
        GPBUtil::checkInt32($var);
        $this->Readonly = $var;

        return $this;
    }

    /**
     * Single file upload
     *
     * Generated from protobuf field <code>optional bytes File = 23;</code>
     * @return string
     */
    public function getFile()
    {
        return isset($this->File) ? $this->File : '';
    }

    public function hasFile()
    {
        return isset($this->File);
    }

    public function clearFile()
    {
        unset($this->File);
    }

    /**
     * Single file upload
     *
     * Generated from protobuf field <code>optional bytes File = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, False);
        $this->File = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Filename = 24;</code>
     * @return string
     */
    public function getFilename()
    {
        return isset($this->Filename) ? $this->Filename : '';
    }

    public function hasFilename()
    {
        return isset($this->Filename);
    }

    public function clearFilename()
    {
        unset($this->Filename);
    }

    /**
     * Generated from protobuf field <code>optional string Filename = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->Filename = $var;

        return $this;
    }

    /**
     * Multi-file upload (list of filenames)
     *
     * Generated from protobuf field <code>repeated string Files = 25;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->Files;
    }

    /**
     * Multi-file upload (list of filenames)
     *
     * Generated from protobuf field <code>repeated string Files = 25;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Files = $arr;

        return $this;
    }

    /**
     * Optional: internal request (used by gateway)
     *
     * Generated from protobuf field <code>optional .InternalRequest IR = 26;</code>
     * @return \InternalRequest|null
     */
    public function getIR()
    {
        return $this->IR;
    }

    public function hasIR()
    {
        return isset($this->IR);
    }

    public function clearIR()
    {
        unset($this->IR);
    }

    /**
     * Optional: internal request (used by gateway)
     *
     * Generated from protobuf field <code>optional .InternalRequest IR = 26;</code>
     * @param \InternalRequest $var
     * @return $this
     */
    public function setIR($var)
    {
        GPBUtil::checkMessage($var, \InternalRequest::class);
        $this->IR = $var;

        return $this;
    }

}

