<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

/**
 * -------------------
 * Upload status
 * -------------------
 *
 * Protobuf type <code>UploadStatusCode</code>
 */
class UploadStatusCode
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>Ok = 1;</code>
     */
    const Ok = 1;
    /**
     * Generated from protobuf enum <code>Failed = 2;</code>
     */
    const Failed = 2;

    private static $valueToName = [
        self::Unknown => 'Unknown',
        self::Ok => 'Ok',
        self::Failed => 'Failed',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

