# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import microservice_pb2 as microservice__pb2


class ReverseStub(object):
    """=============================
    Gufo gRPC Service Definition
    =============================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Do = channel.unary_unary(
                '/Reverse/Do',
                request_serializer=microservice__pb2.Request.SerializeToString,
                response_deserializer=microservice__pb2.Response.FromString,
                )
        self.Stream = channel.stream_stream(
                '/Reverse/Stream',
                request_serializer=microservice__pb2.Request.SerializeToString,
                response_deserializer=microservice__pb2.Response.FromString,
                )


class ReverseServicer(object):
    """=============================
    Gufo gRPC Service Definition
    =============================
    """

    def Do(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReverseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Do': grpc.unary_unary_rpc_method_handler(
                    servicer.Do,
                    request_deserializer=microservice__pb2.Request.FromString,
                    response_serializer=microservice__pb2.Response.SerializeToString,
            ),
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=microservice__pb2.Request.FromString,
                    response_serializer=microservice__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Reverse', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reverse(object):
    """=============================
    Gufo gRPC Service Definition
    =============================
    """

    @staticmethod
    def Do(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reverse/Do',
            microservice__pb2.Request.SerializeToString,
            microservice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Reverse/Stream',
            microservice__pb2.Request.SerializeToString,
            microservice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
