// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: microservice.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReverseClient is the client API for Reverse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Reverse_StreamClient, error)
}

type reverseClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseClient(cc grpc.ClientConnInterface) ReverseClient {
	return &reverseClient{cc}
}

func (c *reverseClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Reverse/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Reverse_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Reverse_ServiceDesc.Streams[0], "/Reverse/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &reverseStreamClient{stream}
	return x, nil
}

type Reverse_StreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type reverseStreamClient struct {
	grpc.ClientStream
}

func (x *reverseStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reverseStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReverseServer is the server API for Reverse service.
// All implementations should embed UnimplementedReverseServer
// for forward compatibility
type ReverseServer interface {
	Do(context.Context, *Request) (*Response, error)
	Stream(Reverse_StreamServer) error
}

// UnimplementedReverseServer should be embedded to have forward compatible implementations.
type UnimplementedReverseServer struct {
}

func (UnimplementedReverseServer) Do(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedReverseServer) Stream(Reverse_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

// UnsafeReverseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseServer will
// result in compilation errors.
type UnsafeReverseServer interface {
	mustEmbedUnimplementedReverseServer()
}

func RegisterReverseServer(s grpc.ServiceRegistrar, srv ReverseServer) {
	s.RegisterService(&Reverse_ServiceDesc, srv)
}

func _Reverse_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Reverse/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reverse_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReverseServer).Stream(&reverseStreamServer{stream})
}

type Reverse_StreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type reverseStreamServer struct {
	grpc.ServerStream
}

func (x *reverseStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reverseStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Reverse_ServiceDesc is the grpc.ServiceDesc for Reverse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reverse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Reverse",
	HandlerType: (*ReverseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Reverse_Do_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Reverse_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "microservice.proto",
}
