# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: microservice.proto for package 'gufo'

require 'grpc'
require 'microservice_pb'

module Gufo
  module Reverse
    # ============================================================
    # Gufo Core Transport (Dynamic Execution Bus)
    # ============================================================
    # - Keeps URL structure compatibility:
    #   /api/v1/{module}/{param}/{param_id}/{param_idd}
    # - Supports HTTP + gRPC
    # - Separates routing, query, and body
    # ============================================================
    #
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gufo.Reverse'

      rpc :Do, ::Gufo::Request, ::Gufo::Response
      rpc :Stream, stream(::Gufo::Request), stream(::Gufo::Response)
    end

    Stub = Service.rpc_stub_class
  end
end
