# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: microservice.proto for package ''

require 'grpc'
require 'microservice_pb'

module Reverse
  # =============================
  # Gufo gRPC Service Definition
  # =============================
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Reverse'

    rpc :Do, ::Request, ::Response
    rpc :Stream, stream(::Request), stream(::Response)
  end

  Stub = Service.rpc_stub_class
end
