# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservice.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("microservice.proto", :syntax => :proto3) do
    add_message "Request" do
      proto3_optional :Module, :string, 1
      proto3_optional :Param, :string, 2
      proto3_optional :ParamID, :string, 3
      proto3_optional :ParamIDD, :string, 4
      proto3_optional :Action, :string, 5
      map :Args, :string, :message, 6, "google.protobuf.Any"
      proto3_optional :Path, :string, 7
      proto3_optional :Token, :string, 8
      proto3_optional :Sign, :string, 9
      proto3_optional :SID, :string, 10
      proto3_optional :IP, :string, 11
      proto3_optional :UserAgent, :string, 12
      proto3_optional :TokenType, :string, 13
      proto3_optional :TimeStamp, :int32, 14
      proto3_optional :Language, :string, 15
      proto3_optional :APIVersion, :string, 16
      proto3_optional :Method, :string, 17
      proto3_optional :UID, :string, 18
      proto3_optional :IsAdmin, :int32, 19
      proto3_optional :SessionEnd, :int32, 20
      proto3_optional :Completed, :int32, 21
      proto3_optional :Readonly, :int32, 22
      proto3_optional :File, :bytes, 23
      proto3_optional :Filename, :string, 24
      repeated :Files, :string, 25
      proto3_optional :IR, :message, 26, "InternalRequest"
    end
    add_message "InternalRequest" do
      proto3_optional :Param, :string, 1
      proto3_optional :ParamID, :string, 2
      proto3_optional :Method, :string, 3
      map :Args, :string, :message, 4, "google.protobuf.Any"
    end
    add_message "Error" do
      optional :code, :int32, 1
      optional :message, :string, 2
      map :meta, :string, :string, 3
    end
    add_message "Response" do
      map :Data, :string, :message, 1, "google.protobuf.Any"
      proto3_optional :RequestBack, :message, 2, "Request"
      proto3_optional :Code, :enum, 3, "UploadStatusCode"
      proto3_optional :error, :message, 4, "Error"
    end
    add_message "FileChunk" do
      optional :name, :string, 1
      optional :data, :bytes, 2
    end
    add_message "StringMap" do
      map :entries, :string, :string, 1
    end
    add_enum "UploadStatusCode" do
      value :Unknown, 0
      value :Ok, 1
      value :Failed, 2
    end
  end
end

Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Request").msgclass
InternalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InternalRequest").msgclass
Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Error").msgclass
Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Response").msgclass
FileChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FileChunk").msgclass
StringMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StringMap").msgclass
UploadStatusCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UploadStatusCode").enummodule
